import type {
	AutoDocEntry,
	AuthorProfile,
	DocHistoryVersionRecord,
	JsAutoDocsIndexOptions
} from './types.js';
type VersionedDocEntry = AutoDocEntry & {
	lastModified: string;
	versionHistory: string[];
};

/**
 * @auto-doc
 * @title Generated Module Emitter
 * @group Output
 * Produces the generated TypeScript module consumed by docs routes.
 * @param docs Parsed docs entries to serialize.
 * @returns TypeScript source code for `src/routes/docs/generated.ts`.
 */
export const createGeneratedModule = (
	docs: VersionedDocEntry[],
	authors: Record<string, AuthorProfile> = {},
	historyByDocId: Record<string, { versions: DocHistoryVersionRecord[] }> = {}
): string => {
	const payload = JSON.stringify(docs, null, 2);
	const authorsPayload = JSON.stringify(authors, null, 2);
	const historyPayload = JSON.stringify(
		Object.fromEntries(
			Object.entries(historyByDocId).map(([docId, record]) => [
				docId,
				(record?.versions ?? []).map((entry) => ({
					version: entry.version,
					changedAt: entry.changedAt,
					snapshot: {
						...entry.snapshot,
						jsdocRaw: entry.snapshot.jsdocRaw ?? '',
						response: entry.snapshot.response ?? '',
						headers: entry.snapshot.headers ?? '',
						body: entry.snapshot.body ?? '',
						fetchUrl: entry.snapshot.fetchUrl ?? ''
					}
				}))
			])
		),
		null,
		2
	);
	return `// This file is generated by jsAutoDocs. Do not edit manually.\n\nexport type GeneratedDocTag = {\n\tname: string;\n\tvalue: string;\n};\n\nexport type GeneratedDocEntry = {\n\tid: string;\n\tslug: string;\n\tgroup: string;\n\ttitle: string;\n\tsummary: string;\n\tdescription: string;\n\tjsdocRaw: string;\n\tsignature: string;\n\tfilePath: string;\n\tline: number;\n\tdisplayPath: string;\n\tparams: GeneratedDocTag[];\n\treturns: string;\n\tresponse: string;\n\theaders: string;\n\tbody: string;\n\tfetchUrl: string;\n\texamples: string[];\n\ttags: GeneratedDocTag[];\n\tlastModified: string;\n\tversionHistory: string[];\n};\n\nexport type GeneratedDocSnapshot = Pick<\n\tGeneratedDocEntry,\n\t'group' | 'title' | 'summary' | 'description' | 'jsdocRaw' | 'signature' | 'displayPath' | 'params' | 'returns' | 'response' | 'headers' | 'body' | 'fetchUrl' | 'examples' | 'tags'\n>;\n\nexport type GeneratedDocVersionRecord = {\n\tversion: string;\n\tchangedAt: string;\n\tsnapshot: GeneratedDocSnapshot;\n};\n\nexport type GeneratedAuthorProfile = {\n\tname: string;\n\ttitle?: string;\n\tusername?: string;\n\tbio?: string;\n\timageUrl?: string;\n\temail?: string;\n\taddress?: string;\n\tphone?: Partial<Record<'mobile' | 'office' | 'home' | 'other', string>>;\n\tlinks?: Record<string, string>;\n};\n\nexport const generatedAt = ${JSON.stringify(new Date().toISOString())};\n\nexport const docs: GeneratedDocEntry[] = ${payload};\n\nexport const authors: Record<string, GeneratedAuthorProfile> = ${authorsPayload};\n\nexport const history: Record<string, GeneratedDocVersionRecord[]> = ${historyPayload};\n`;
};

/**
 * @auto-doc
 * @title Docs Settings Module Emitter
 * @group Output
 * Emits a tiny settings module used by docs routes to determine runtime visibility.
 * @param enabled Whether docs routes should be visible in the current build mode.
 * @returns TypeScript source for `src/routes/docs/settings.ts`.
 */
export const createDocsSettingsModule = (enabled: boolean): string => {
	return `// This file is generated by jsAutoDocs. Do not edit manually.\n\nexport const docsEnabled = ${enabled ? 'true' : 'false'};\n`;
};

/**
 * @auto-doc
 * @title Docs Layout Load Emitter
 * @group Output
 * Produces generated load logic for `/docs/+layout.ts`.
 * @returns TypeScript source for shared docs layout data and visibility guard.
 */
export const createDocsLayoutTsModule = (): string => {
	return `import { error } from '@sveltejs/kit';
import type { LayoutLoad } from './$types';
import { docs, generatedAt } from './generated';
import { docsEnabled } from './settings';

/**
 * Loads shared docs data for all \`/docs\` routes.
 * Entries are ordered by case-sensitive group and then by case-sensitive title.
 */
export const load: LayoutLoad = async () => {
	if (!docsEnabled) {
		throw error(404, 'Not found');
	}

	const compareAlphabetical = (left: string, right: string): number => {
		const folded = left.localeCompare(right, undefined, { sensitivity: 'base' });
		if (folded !== 0) return folded;
		return left.localeCompare(right);
	};

	const sortedDocs = [...docs].sort((a, b) => {
		const groupOrder = compareAlphabetical(a.group || '', b.group || '');
		if (groupOrder !== 0) return groupOrder;
		return compareAlphabetical(a.title, b.title);
	});

	return {
		docs: sortedDocs,
		generatedAt
	};
};
`;
};

/**
 * @auto-doc
 * @title Docs Layout Scaffold Emitter
 * @group Output
 * Produces the generated `/docs/+layout.svelte` scaffold consumed by projects using the plugin.
 * @param docsTitle Sidebar heading shown above docs navigation.
 * @returns Svelte source for docs navigation layout with fuzzy search support.
 */
export const createDocsLayoutSvelteModule = (
	docsTitle = 'SvelteJSDoc',
	logo?: string,
	navbarCollapsed = true
): string => {
	const docsTitleLiteral = JSON.stringify(docsTitle);
	const logoLiteral = JSON.stringify(logo ?? null);
	const navbarCollapsedLiteral = navbarCollapsed ? 'true' : 'false';
	return `<script lang="ts">
	import { page } from '$app/state';
	import type { LayoutData } from './$types';

	let { data, children }: { data: LayoutData; children: import('svelte').Snippet } = $props();
	let searchQuery = $state('');
	const navbarCollapsedByDefault = ${navbarCollapsedLiteral};
	let toggledGroupPaths = $state(new Set<string>());
	let sidebarOpen = $state(true);
	const docsTitle = ${docsTitleLiteral};
	const docsLogo = ${logoLiteral};
	const logoSrc = docsLogo
		? /^(https?:\\/\\/|\\/)/.test(docsLogo)
			? docsLogo
			: "/" + docsLogo.replace(/^\\.\\/+/, '').replace(/^\\/+/, '')
		: null;

	const normalizeText = (value: string): string => value.toLowerCase().replace(/[^a-z0-9]/g, '');

	const fuzzyScore = (query: string, target: string): number => {
		const q = normalizeText(query);
		const t = normalizeText(target);
		if (!q.length) return 0;
		if (!t.length) return -1;

		const directIndex = t.indexOf(q);
		if (directIndex >= 0) {
			return 1200 - directIndex * 2 - (t.length - q.length);
		}

		let qIndex = 0;
		let lastMatch = -1;
		let gapPenalty = 0;
		let streak = 0;
		let bestStreak = 0;

		for (let i = 0; i < t.length && qIndex < q.length; i += 1) {
			if (t[i] !== q[qIndex]) continue;

			if (lastMatch >= 0) {
				gapPenalty += Math.max(0, i - lastMatch - 1);
			}

			streak = i === lastMatch + 1 ? streak + 1 : 1;
			bestStreak = Math.max(bestStreak, streak);
			lastMatch = i;
			qIndex += 1;
		}

		if (qIndex !== q.length) return -1;

		return 700 - gapPenalty * 3 + bestStreak * 12 - (t.length - q.length);
	};

	const docScore = (query: string, doc: LayoutData['docs'][number]): number => {
		const fields = [doc.title, doc.displayPath, doc.group, doc.summary, doc.filePath];
		let best = -1;
		for (const field of fields) {
			best = Math.max(best, fuzzyScore(query, field));
		}
		return best;
	};

	const groupToSegments = (group: string): string[] =>
		group.split('/').map((segment) => segment.trim()).filter(Boolean);

	const expandGroupPaths = (group: string): string[] => {
		const segments = groupToSegments(group);
		if (segments.length === 0) return ['Ungrouped'];

		const paths: string[] = [];
		for (let i = 0; i < segments.length; i += 1) {
			paths.push(segments.slice(0, i + 1).join('/'));
		}
		return paths;
	};

	const groupHref = (groupPath: string): string =>
		groupPath === 'Ungrouped'
			? '/docs/groups/Ungrouped'
			: '/docs/groups/' + groupToSegments(groupPath).map((segment) => encodeURIComponent(segment)).join('/');

	const compareAlphabetical = (left: string, right: string): number => {
		const folded = left.localeCompare(right, undefined, { sensitivity: 'base' });
		if (folded !== 0) return folded;
		return left.localeCompare(right);
	};

	const toggleGroup = (groupPath: string): void => {
		if (searchQuery.trim().length > 0) return;
		const next = new Set(toggledGroupPaths);
		if (next.has(groupPath)) {
			next.delete(groupPath);
		} else {
			next.add(groupPath);
		}
		toggledGroupPaths = next;
	};

	const isGroupCollapsed = (groupPath: string): boolean =>
		searchQuery.trim().length === 0 && (navbarCollapsedByDefault ? !toggledGroupPaths.has(groupPath) : toggledGroupPaths.has(groupPath));

	const toggleSidebar = (): void => {
		sidebarOpen = !sidebarOpen;
	};

	const getMethodValue = (doc: LayoutData['docs'][number]): string | null => {
		const methodTag = doc.tags.find((tag) => tag.name.toLowerCase() === 'method');
		const value = methodTag?.value.trim().toUpperCase();
		return value || null;
	};

	const methodTextClass = (method: string | null): string => {
		switch (method) {
			case 'POST':
				return 'text-blue-300';
			case 'PUT':
				return 'text-orange-400';
				case 'PATCH':
					return 'text-amber-300';
			case 'DELETE':
				return 'text-rose-300';
			case 'GET':
				return 'text-emerald-300';
			default:
				return 'text-cyan-300';
		}
	};

	const groupedDocs = $derived.by(() => {
		const query = searchQuery.trim();
		const groups = new Map<string, Array<{ doc: LayoutData['docs'][number]; score: number }>>();
		const allGroupPaths = new Set<string>();

		for (const doc of data.docs) {
			const score = query ? docScore(query, doc) : 0;
			if (query && score < 0) continue;

			const key = doc.group || 'Ungrouped';
			for (const path of expandGroupPaths(key)) {
				allGroupPaths.add(path);
			}
			if (!groups.has(key)) groups.set(key, []);
			groups.get(key)?.push({ doc, score });
		}

		for (const docsInGroup of groups.values()) {
			docsInGroup.sort((left, right) => {
				if (query) {
					const scoreDelta = right.score - left.score;
					if (scoreDelta !== 0) return scoreDelta;
				}

				return compareAlphabetical(left.doc.title, right.doc.title);
			});
		}

		return [...allGroupPaths]
			.sort((a, b) => {
				return compareAlphabetical(a, b);
			})
			.map((groupName) => {
				const docsInGroup = groups.get(groupName) ?? [];
				const segments = groupToSegments(groupName);
				const ancestors = segments.slice(0, -1).map((_, index) => segments.slice(0, index + 1).join('/'));
				return {
				groupName,
				groupPath: groupName,
				depth: Math.max(0, segments.length - 1),
				label: segments.length > 0 ? segments[segments.length - 1] : groupName,
				ancestors,
				docs: docsInGroup.map((entry) => entry.doc)
				};
			});
	});
</script>

	<section class="min-h-screen bg-zinc-50 text-zinc-950 lg:min-h-screen">
		{#if !sidebarOpen}
			<button
				type="button"
				onclick={toggleSidebar}
				class="fixed left-4 top-4 z-40 border border-zinc-800 bg-zinc-950 px-3 py-2 text-[11px] font-bold tracking-[0.18em] text-zinc-100 uppercase shadow-lg transition hover:border-cyan-400 hover:text-cyan-200"
				aria-label="Open navigation"
			>
				Menu
			</button>
		{/if}

		{#if sidebarOpen}
			<button
				type="button"
				onclick={toggleSidebar}
				class="fixed inset-0 z-20 bg-zinc-950/45 lg:hidden"
				aria-label="Close navigation overlay"
			></button>
		{/if}

		<aside
			class={\`fixed inset-y-0 left-0 z-30 flex w-[17rem] flex-col border-r border-zinc-800 bg-zinc-950 text-zinc-100 transition-transform duration-300 ease-out \${sidebarOpen ? 'translate-x-0' : '-translate-x-full'}\`}
		>
			<div class="border-b border-zinc-800 px-5 py-5">
				<div class="flex items-start justify-between gap-3">
					<div class="flex items-center gap-3 min-w-0">
					{#if logoSrc}
						<img
							src={logoSrc}
							alt={docsTitle}
							class="h-8 w-8 shrink-0 rounded border border-zinc-700 bg-zinc-900/70 object-contain p-1"
						/>
					{/if}
						<h1 class="truncate text-xl font-black tracking-tight">{docsTitle}</h1>
					</div>
					<button
						type="button"
						onclick={toggleSidebar}
						class="shrink-0 border border-zinc-700 px-2 py-1 text-[10px] font-bold tracking-[0.18em] text-zinc-300 uppercase transition hover:border-cyan-400 hover:text-cyan-200"
						aria-label="Collapse navigation"
					>
						Hide
					</button>
				</div>
			</div>

			<div class="border-b border-zinc-800 px-5 py-4">
				<input
					id="docs-search"
					type="search"
					bind:value={searchQuery}
					placeholder="Search docs..."
					class="mt-2 w-full border border-zinc-700 bg-zinc-900 px-3 py-2 text-xs text-zinc-100 placeholder:text-zinc-500 focus:border-cyan-400 focus:outline-none"
				/>
			</div>

			<nav
				class="max-h-[42vh] overflow-y-auto lg:min-h-0 lg:flex-1 lg:max-h-none"
				aria-label="Documentation navigation"
			>
				<ul>
					<li>
						<a
							href="/docs"
							class={\`block border-b border-zinc-800 px-5 py-3 text-xs font-semibold tracking-wide uppercase transition \${page.url.pathname === '/docs' ? 'bg-zinc-800 text-cyan-200' : 'text-zinc-300 hover:bg-zinc-900 hover:text-white'}\`}
						>
							Home
						</a>
					</li>
					{#if groupedDocs.length === 0}
						<li class="border-b border-zinc-800 px-5 py-4 text-xs text-zinc-400">
							No matches for "{searchQuery.trim()}"
						</li>
					{/if}
					{#each groupedDocs as groupEntry (\`\${groupEntry.groupPath}\`)}
						{#if !groupEntry.ancestors.some((ancestor) => isGroupCollapsed(ancestor))}
							<li class="border-b border-zinc-800">
								<div class="flex items-center bg-zinc-900" style={\`padding-left: \${1.25 + groupEntry.depth * 0.9}rem; padding-right: 0.5rem;\`}>
									<button
										type="button"
										class="mr-1 cursor-pointer p-1 text-zinc-500 hover:text-cyan-300"
										onclick={() => toggleGroup(groupEntry.groupPath)}
										aria-label={\`Toggle \${groupEntry.label}\`}
									>
										{isGroupCollapsed(groupEntry.groupPath) ? '▸' : '▾'}
									</button>
									<a
										href={groupHref(groupEntry.groupPath)}
										class="flex-1 py-2 text-[10px] font-semibold tracking-[0.18em] text-zinc-400 uppercase hover:text-cyan-200"
									>
										{groupEntry.label}
									</a>
								</div>
								{#if !isGroupCollapsed(groupEntry.groupPath)}
									<ul>
										{#each groupEntry.docs as doc (\`\${doc.id}\`)}
											<li>
												<a
													href={\`/docs/\${doc.slug}\`}
													class={\`block border-t border-zinc-800 py-3 text-xs transition \${page.url.pathname === \`/docs/\${doc.slug}\` ? 'bg-zinc-800 text-cyan-200' : 'text-zinc-300 hover:bg-zinc-900 hover:text-white'}\`}
													style={\`padding-left: \${1.7 + groupEntry.depth * 0.9}rem; padding-right: 1rem;\`}
												>
														<div class="flex items-start justify-between gap-3">
															<p class="min-w-0 flex-1 font-semibold tracking-wide uppercase">{doc.title}</p>
															{#if getMethodValue(doc)}
																<span class={\`shrink-0 text-[10px] font-black tracking-[0.18em] uppercase \${methodTextClass(getMethodValue(doc))}\`}>{getMethodValue(doc)}</span>
															{/if}
														</div>
													<p class="mt-1 truncate text-[10px] text-zinc-500">{doc.displayPath}</p>
												</a>
											</li>
										{/each}
									</ul>
								{/if}
							</li>
						{/if}
					{/each}
				</ul>
			</nav>
		</aside>

		<main class={\`min-h-screen bg-white px-6 py-8 text-zinc-950 transition-[margin] duration-300 ease-out sm:px-10 \${sidebarOpen ? 'lg:ml-68' : 'lg:ml-0'}\`}>
			{@render children()}
		</main>
</section>
`;
};

/**
 * @auto-doc
 * @title Docs Index Load Emitter
 * @group Output
 * Produces generated load logic for `/docs/+page.ts`.
 * @returns TypeScript source that provides sorted docs list and generation timestamp.
 */
export const createDocsIndexPageTsModule = (): string => {
	return `import type { PageLoad } from './$types';
import { authors, docs, generatedAt } from './generated';

/** Loads data required by the docs overview page. */
export const load: PageLoad = async () => {
	const sortedAuthors = Object.entries(authors)
		.map(([key, profile]) => ({ key, ...profile }))
		.sort((left, right) => left.name.localeCompare(right.name));

	return {
		docs: [...docs].sort((a, b) => a.title.localeCompare(b.title)),
		authors: sortedAuthors,
		generatedAt
	};
};
`;
};

/**
 * @auto-doc
 * @title Docs Index Page Emitter
 * @group Output
 * Produces generated UI source for `/docs/+page.svelte`.
 * @returns Svelte source for docs overview grouped listing.
 */
export const createDocsIndexPageSvelteModule = (indexOptions: JsAutoDocsIndexOptions = {}): string => {
	const defaults = {
		tagline: 'DOCUMENTATION',
		heading: 'Documentation Home',
		description: 'JSDoc auto generated documentation for developers.'
	};

	const taglineLiteral = JSON.stringify(indexOptions.tagline ?? defaults.tagline);
	const headingLiteral = JSON.stringify(indexOptions.heading ?? defaults.heading);
	const descriptionLiteral = JSON.stringify(indexOptions.description ?? defaults.description);

	return `<script lang="ts">
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();
	const homeTagline = ${taglineLiteral};
	const homeHeading = ${headingLiteral};
	const homeDescription = ${descriptionLiteral};
	const normalizeAssetSrc = (value?: string): string | null =>
		value
			? /^(https?:\\/\\/|\\/)/.test(value)
				? value
				: '/' + value.replace(/^\\.\\/+/, '').replace(/^\\/+/, '')
			: null;

	const groupHref = (groupName: string): string => {
		const parts = groupName.split('/').map((segment) => segment.trim()).filter(Boolean);
		if (parts.length === 0) return '/docs/groups/Ungrouped';
		return '/docs/groups/' + parts.map((segment) => encodeURIComponent(segment)).join('/');
	};

	const groupedDocs = $derived.by(() => {
		const groups = new Map<string, PageData['docs']>();
		for (const doc of data.docs) {
			const key = doc.group || 'Ungrouped';
			if (!groups.has(key)) groups.set(key, []);
			groups.get(key)?.push(doc);
		}

		for (const docsInGroup of groups.values()) {
			docsInGroup.sort((left, right) => {
				if (left.title === right.title) return 0;
				return left.title < right.title ? -1 : 1;
			});
		}

		return [...groups.entries()].sort(([a], [b]) => {
			if (a === b) return 0;
			return a < b ? -1 : 1;
		});
	});
</script>

<div class="docs-home mx-auto max-w-5xl">
	<header class="border-b border-zinc-300 pb-6 docs-home-header">
		<p class="text-[10px] font-semibold tracking-[0.24em] text-cyan-700 uppercase">
			{homeTagline}
		</p>
		<h2
			class="docs-home-title mt-2 text-4xl leading-tight font-black tracking-tight text-zinc-900"
		>
			{homeHeading}
		</h2>
		<p class="docs-home-summary mt-3 max-w-3xl text-sm text-zinc-900">
			{homeDescription}
		</p>
	</header>

	{#if data.authors.length > 0}
		<section class="mt-6 docs-home-authors">
			<div class="mb-2 flex items-center justify-between">
				<h3 class="text-[11px] font-bold tracking-[0.16em] text-zinc-900 uppercase">Contributors</h3>
				<p class="text-xs text-zinc-700">{data.authors.length} listed</p>
			</div>
			<ul class="grid gap-2 sm:grid-cols-2">
				{#each data.authors as author (\`\${author.key}\`)}
					{@const authorImageSrc = normalizeAssetSrc(author.imageUrl)}
					<li class="docs-author-chip border border-zinc-300 bg-zinc-50 px-3 py-2">
						<a href={\`/docs/authors/\${author.key}\`} class="block hover:text-cyan-700">
						<div class="flex items-center gap-2.5">
							{#if authorImageSrc}
								<img
									src={authorImageSrc}
									alt={author.name}
									class="h-8 w-8 rounded-full border border-zinc-300 object-cover"
								/>
							{/if}
							<div class="min-w-0">
								<p class="truncate text-sm font-semibold text-zinc-900">{author.name}</p>
								{#if author.title}
									<p class="truncate text-xs text-zinc-700">{author.title}</p>
								{/if}
							</div>
						</div>
						</a>
					</li>
				{/each}
			</ul>
		</section>
	{/if}

	{#if data.docs.length === 0}
		<div
			class="mt-8 border border-dashed border-zinc-400 bg-white p-8 docs-home-empty"
		>
			<h3 class="text-lg font-bold text-zinc-900">No entries found</h3>
			<p class="mt-2 text-sm text-zinc-800">
				Add an eligible JSDoc block and rebuild or refresh dev mode.
			</p>
		</div>
	{:else}
		{#each groupedDocs as [groupName, docsInGroup] (\`\${groupName}\`)}
			<section
				class="docs-home-section mt-8 overflow-hidden border border-zinc-300 bg-white"
			>
				<div
					class="border-b border-zinc-300 bg-zinc-900 px-4 py-2 text-[10px] font-semibold tracking-[0.2em] text-zinc-300 uppercase"
				>
					<a href={groupHref(groupName)} class="hover:text-cyan-200">{groupName}</a>
				</div>
				<div
					class="docs-home-columns grid grid-cols-[minmax(0,2fr)_minmax(0,1.2fr)_auto] border-b border-zinc-300 bg-zinc-100 px-4 py-3 text-[10px] font-semibold tracking-[0.18em] text-zinc-700 uppercase"
				>
					<span>Doc</span>
					<span>Source</span>
					<span>Params</span>
				</div>
				<ul>
					{#each docsInGroup as doc, index (\`\${doc.id}\`)}
						<li
							class={\`grid grid-cols-[minmax(0,2fr)_minmax(0,1.2fr)_auto] items-start gap-3 px-4 py-4 \${index < docsInGroup.length - 1 ? 'border-b border-zinc-200' : ''}\`}
						>
							<div class="min-w-0">
								<a
									href={\`/docs/\${doc.slug}\`}
									class="font-semibold text-zinc-900 hover:text-cyan-700"
									>{doc.title}</a
								>
								<p class="mt-1 text-sm text-zinc-900">{doc.summary}</p>
							</div>
							<p class="pt-0.5 text-xs text-zinc-800">
								{doc.displayPath ?? \`\${doc.filePath}:\${doc.line}\`}
							</p>
							<p class="pt-0.5 text-xs font-semibold text-zinc-800">
								{doc.params.length}
							</p>
						</li>
					{/each}
				</ul>
			</section>
		{/each}
	{/if}
</div>

`;
};

/**
 * @auto-doc
 * @title Group Detail Load Emitter
 * @group Output
 * Produces generated load logic for `/docs/groups/[group]/+page.ts`.
 * @returns TypeScript source for docs group landing page data.
 */
export const createDocsGroupPageTsModule = (): string => {
	return `import { error } from '@sveltejs/kit';
import type { PageLoad } from './$types';
import { docs } from '../../generated';

const decodeGroupParam = (value: string): string => {
	try {
		return decodeURIComponent(value);
	} catch {
		return value;
	}
};

const parseGroupSegments = (value: string): string[] =>
	value
		.split('/')
		.map((segment) => decodeGroupParam(segment).trim())
		.filter(Boolean);

/** Loads entries for a single docs group and preserves title ordering. */
export const load: PageLoad = async ({ params }) => {
	const groupPathRaw = params.groupPath ?? '';
	const segments = parseGroupSegments(groupPathRaw);
	const groupName = segments.join('/');

	if (!groupName) {
		throw error(404, 'Documentation group not found');
	}

	const entries = docs
		.filter((doc) => (doc.group || 'Ungrouped') === groupName)
		.sort((a, b) => a.title.localeCompare(b.title));

	const childGroupMap = new Map<string, { path: string; name: string; docCount: number }>();
	const prefix = groupName + '/';
	for (const doc of docs) {
		const group = doc.group || 'Ungrouped';
		if (!group.startsWith(prefix)) continue;
		const remainder = group.slice(prefix.length);
		const [nextSegment] = remainder.split('/');
		if (!nextSegment) continue;
		const childPath = \`\${groupName}/\${nextSegment}\`;
		const existing = childGroupMap.get(childPath);
		if (existing) {
			existing.docCount += 1;
			continue;
		}
		childGroupMap.set(childPath, {
			path: childPath,
			name: nextSegment,
			docCount: 1
		});
	}

	const childGroups = [...childGroupMap.values()].sort((a, b) => a.path.localeCompare(b.path));

	if (entries.length === 0 && childGroups.length === 0) {
		throw error(404, 'Documentation group not found');
	}

	return {
		groupName,
		segments,
		docs: entries,
		childGroups
	};
};
`;
};

/**
 * @auto-doc
 * @title Group Detail Page Emitter
 * @group Output
 * Produces generated UI source for `/docs/groups/[group]/+page.svelte`.
 * @returns Svelte source for a docs group landing page.
 */
export const createDocsGroupPageSvelteModule = (): string => {
	return `<script lang="ts">
	import { resolve } from '$app/paths';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();

	const groupCrumbs = $derived(
		data.segments.map((segment, index) => ({
			label: segment,
			path: data.segments.slice(0, index + 1).join('/')
		}))
	);

	const groupHref = (groupPath: string): string =>
		'/docs/groups/' +
		groupPath
			.split('/')
			.map((segment) => encodeURIComponent(segment))
			.join('/');
</script>

<div class="docs-group mx-auto max-w-5xl">
	<div class="border-b border-zinc-300 pb-4">
		<nav class="flex items-center gap-2 text-xs font-semibold tracking-wide uppercase" aria-label="Breadcrumb">
			<a href={resolve('/docs')} class="text-zinc-900 hover:text-cyan-700">All docs</a>
			{#each groupCrumbs as crumb, index (\`\${crumb.path}\`)}
				<span class="text-zinc-500">/</span>
				{#if index < groupCrumbs.length - 1}
					<a href={groupHref(crumb.path)} class="text-zinc-900 hover:text-cyan-700">{crumb.label}</a>
				{:else}
					<span class="text-zinc-700">{crumb.label}</span>
				{/if}
			{/each}
		</nav>
	</div>

	<article class="mt-4 border border-zinc-300 bg-white p-6 sm:p-8">
		<p class="text-[10px] font-semibold tracking-[0.2em] text-cyan-700 uppercase">Group</p>
		<h1 class="mt-2 text-3xl font-black tracking-tight text-zinc-950">{data.groupName}</h1>
		<p class="mt-2 text-sm text-zinc-800">{data.docs.length} {data.docs.length === 1 ? 'entry' : 'entries'} in this group</p>

		{#if data.childGroups.length > 0}
			<section class="mt-6 border border-zinc-200 bg-zinc-50 p-4">
				<p class="text-[10px] font-semibold tracking-[0.18em] text-zinc-700 uppercase">Subgroups</p>
				<ul class="mt-3 space-y-2">
					{#each data.childGroups as child (\`\${child.path}\`)}
						<li class="flex items-center justify-between gap-3 border border-zinc-200 bg-white px-3 py-2">
							<a href={groupHref(child.path)} class="text-sm font-semibold text-zinc-900 hover:text-cyan-700">{child.name}</a>
							<span class="text-xs text-zinc-700">{child.docCount} {child.docCount === 1 ? 'entry' : 'entries'}</span>
						</li>
					{/each}
				</ul>
			</section>
		{/if}

		{#if data.docs.length > 0}
			<ul class="mt-6 space-y-3">
				{#each data.docs as doc (\`\${doc.id}\`)}
					<li class="border border-zinc-200 bg-zinc-50 px-4 py-3">
						<a href={resolve(\`/docs/\${doc.slug}\`)} class="text-sm font-semibold text-zinc-900 hover:text-cyan-700">{doc.title}</a>
						<p class="mt-1 text-xs text-zinc-700">{doc.displayPath}</p>
						{#if doc.summary}
							<p class="mt-2 text-sm text-zinc-900">{doc.summary}</p>
						{/if}
					</li>
				{/each}
			</ul>
		{/if}
	</article>
</div>
`;
};


/**
 * @auto-doc
 * @title Docs Detail Load Emitter
 * @group Output
 * Produces generated load logic for `/docs/[slug]/+page.server.ts` including author matching and code highlighting.
 * @returns TypeScript source for slug detail loader.
 */
export const createDocsSlugPageTsModule = (collapseJson = false): string => {
	const collapseJsonLiteral = collapseJson ? 'true' : 'false';
	return `import path from 'node:path';
import { error } from '@sveltejs/kit';
import type { PageServerLoad } from './$types';
import { createHighlighter } from 'shiki';
import { authors, docs, type GeneratedAuthorProfile } from '../generated';

type HighlightLanguage =
	| 'javascript'
	| 'typescript'
	| 'json'
	| 'jsx'
	| 'tsx'
	| 'svelte'
	| 'python'
	| 'ruby'
	| 'php'
	| 'java'
	| 'go'
	| 'rust'
	| 'c'
	| 'cpp'
	| 'csharp'
	| 'html'
	| 'css'
	| 'scss'
	| 'markdown'
	| 'yaml'
	| 'bash';

type HighlightedExample = {
	key: string;
	label: string | null;
	html: string;
};

const collapseJson = ${collapseJsonLiteral};
const highlighterCache = globalThis as typeof globalThis & {
	__sveltejsdocHighlighterPromise__?: ReturnType<typeof createHighlighter>;
};
const highlightLangs: HighlightLanguage[] = [
	'javascript',
	'typescript',
	'json',
	'jsx',
	'tsx',
	'svelte',
	'python',
	'ruby',
	'php',
	'java',
	'go',
	'rust',
	'c',
	'cpp',
	'csharp',
	'html',
	'css',
	'scss',
	'markdown',
	'yaml',
	'bash'
];

const getHighlighter = () => {
	if (!highlighterCache.__sveltejsdocHighlighterPromise__) {
		highlighterCache.__sveltejsdocHighlighterPromise__ = createHighlighter({
			themes: ['github-light'],
			langs: highlightLangs
		});
	}

	return highlighterCache.__sveltejsdocHighlighterPromise__;
};

const normalizeAuthorKey = (value: string): string => value.trim().replace(/^@/, '').toLowerCase();

const inferExampleLanguage = (label: string | null, content: string): HighlightLanguage => {
	const normalizedLabel = label?.trim().toLowerCase() ?? '';
	const trimmed = content.trim();

	if (
		normalizedLabel.includes('curl') ||
		normalizedLabel.includes('shell') ||
		normalizedLabel.includes('bash') ||
		trimmed.startsWith('curl ') ||
		trimmed.startsWith('HTTP/')
	) {
		return 'bash';
	}

	if (isJsonBlock(trimmed)) {
		return 'json';
	}

	return 'javascript';
};

const splitExampleContent = (example: string, index: number): { key: string; label: string | null; content: string; language: HighlightLanguage } => {
	const trimmed = example.trim();
	const lines = trimmed.split('\\n');
	const firstLine = lines[0]?.trim() ?? '';
	const remainder = lines.slice(1).join('\\n').trim();
	const canUseFirstLineAsLabel =
		Boolean(remainder) &&
		/^[A-Za-z][A-Za-z0-9 /_+-]{0,40}:?$/.test(firstLine) &&
		!/[{}()[\]=;]/.test(firstLine);
	const label = canUseFirstLineAsLabel ? firstLine.replace(/:$/, '') : null;
	const content = canUseFirstLineAsLabel ? remainder : trimmed;

	return {
		key: 'example-' + index,
		label,
		content,
		language: inferExampleLanguage(label, content)
	};
};

const candidateKeysFromTag = (raw: string): string[] => {
	const cleaned = raw.trim();
	if (!cleaned) return [];

	const parts = cleaned
		.split(/[\\s,|]+/)
		.map((part) => normalizeAuthorKey(part))
		.filter(Boolean);

	const full = normalizeAuthorKey(cleaned);
	return [...new Set([full, ...parts])];
};

const resolveAuthor = (tagValue: string): { key: string; profile: GeneratedAuthorProfile } | null => {
	for (const key of candidateKeysFromTag(tagValue)) {
		const profile = authors[key];
		if (profile) return { key, profile };
	}

	return null;
};

const isJsonBlock = (value: string): boolean => {
	const trimmed = value.trim();
	if (!trimmed) return false;
	if (!((trimmed.startsWith('{') && trimmed.endsWith('}')) || (trimmed.startsWith('[') && trimmed.endsWith(']')))) {
		return false;
	}

	try {
		JSON.parse(trimmed);
		return true;
	} catch {
		return false;
	}
};

const isTypeObject = (value: string): boolean => {
	const trimmed = value.trim();
	return trimmed.startsWith('{') && trimmed.endsWith('}');
};

const extractJsonBlock = (value: string): { value: string; remainder: string } | null => {
	const trimmed = value.trim();
	if (!trimmed) return null;

	if (isJsonBlock(trimmed)) {
		return {
			value: trimmed,
			remainder: ''
		};
	}

	const lines = value.split('\\n');

	for (let start = 0; start < lines.length; start += 1) {
		const startTrimmed = lines[start].trim();
		if (!(startTrimmed.startsWith('{') || startTrimmed.startsWith('['))) continue;

		for (let end = start; end < lines.length; end += 1) {
			const candidate = lines.slice(start, end + 1).join('\\n').trim();
			if (!isJsonBlock(candidate)) continue;

			const before = lines.slice(0, start).join('\\n').trimEnd();
			const after = lines.slice(end + 1).join('\\n').trimStart();
			return {
				value: candidate,
				remainder: [before, after].filter(Boolean).join('\\n\\n').trim()
			};
		}
	}

	return null;
};

const formatTypeObject = (value: string): string => {
	const source = value.trim();
	if (!source) return '';

	const indentUnit = '  ';
	let out = '';
	let depth = 0;
	let inSingleQuote = false;
	let inDoubleQuote = false;
	let escaped = false;

	const isWhitespace = (ch: string): boolean => ch === ' ' || ch === '\\n' || ch === '\\r' || ch === '\\t';
	const appendIndent = (count: number): void => {
		if (count <= 0) return;
		out += indentUnit.repeat(count);
	};
	const nextNonWhitespace = (start: number): string => {
		for (let i = start; i < source.length; i += 1) {
			const ch = source[i];
			if (!isWhitespace(ch)) return ch;
		}
		return '';
	};

	for (let i = 0; i < source.length; i += 1) {
		const ch = source[i];

		if (inSingleQuote || inDoubleQuote) {
			out += ch;
			if (escaped) {
				escaped = false;
				continue;
			}
			if (ch === '\\\\') {
				escaped = true;
				continue;
			}
			if (inSingleQuote && ch === "'") {
				inSingleQuote = false;
			} else if (inDoubleQuote && ch === '"') {
				inDoubleQuote = false;
			}
			continue;
		}

		if (ch === "'") {
			inSingleQuote = true;
			out += ch;
			continue;
		}

		if (ch === '"') {
			inDoubleQuote = true;
			out += ch;
			continue;
		}

		if (collapseJson) {
			if (isWhitespace(ch)) {
				if (out.length > 0 && out[out.length - 1] !== ' ') out += ' ';
				continue;
			}
			out += ch;
			continue;
		}

		if (isWhitespace(ch)) {
			if (out.endsWith('\\n')) continue;
			if (!out.endsWith(' ')) out += ' ';
			continue;
		}

		if (ch === '{' || ch === '[') {
			out += ch;
			depth += 1;
			const closing = ch === '{' ? '}' : ']';
			if (nextNonWhitespace(i + 1) !== closing) {
				out += '\\n';
				appendIndent(depth);
			}
			continue;
		}

		if (ch === '}' || ch === ']') {
			depth = Math.max(0, depth - 1);
			while (out.endsWith(' ')) out = out.slice(0, -1);
			if (!out.endsWith('\\n') && out.length > 0) {
				out += '\\n';
			}
			appendIndent(depth);
			out += ch;
			continue;
		}

		if (ch === ',') {
			out += ',\\n';
			appendIndent(depth);
			continue;
		}

		if (ch === ':') {
			while (out.endsWith(' ')) out = out.slice(0, -1);
			out += ': ';
			continue;
		}

		if (ch === '|') {
			while (out.endsWith(' ')) out = out.slice(0, -1);
			out += ' | ';
			continue;
		}

		out += ch;
	}

	return out.trim();
};

const detectLanguage = (value: string, fallback: HighlightLanguage = 'javascript'): HighlightLanguage => {
	if (isJsonBlock(value)) return 'json';
	if (isTypeObject(value)) return 'typescript';
	return fallback;
};

const languageFromFilePath = (filePath: string): HighlightLanguage => {
	switch (path.extname(filePath).toLowerCase()) {
		case '.ts':
		case '.mts':
		case '.cts':
			return 'typescript';
		case '.tsx':
			return 'tsx';
		case '.js':
		case '.mjs':
		case '.cjs':
			return 'javascript';
		case '.jsx':
			return 'jsx';
		case '.svelte':
			return 'svelte';
		case '.py':
			return 'python';
		case '.rb':
			return 'ruby';
		case '.php':
			return 'php';
		case '.java':
			return 'java';
		case '.go':
			return 'go';
		case '.rs':
			return 'rust';
		case '.c':
			return 'c';
		case '.cc':
		case '.cpp':
		case '.cxx':
		case '.hpp':
		case '.hh':
		case '.hxx':
		case '.h':
			return 'cpp';
		case '.cs':
			return 'csharp';
		case '.html':
		case '.htm':
			return 'html';
		case '.css':
			return 'css';
		case '.scss':
			return 'scss';
		case '.md':
		case '.mdx':
			return 'markdown';
		case '.yaml':
		case '.yml':
			return 'yaml';
		case '.sh':
		case '.bash':
		case '.zsh':
			return 'bash';
		case '.json':
			return 'json';
		default:
			return 'typescript';
	}
};

const normalizeCodeForHighlight = (value: string, language: HighlightLanguage): string => {
	if (language === 'json' && isJsonBlock(value)) {
		const parsed = JSON.parse(value);
		return collapseJson ? JSON.stringify(parsed) : JSON.stringify(parsed, null, 2);
	}

	if (language === 'typescript' && isTypeObject(value)) {
		return formatTypeObject(value);
	}

	return value;
};

const highlightCode = async (value: string, fallback: HighlightLanguage = 'javascript'): Promise<string> => {
	const language = detectLanguage(value, fallback);
	const highlighter = await getHighlighter();
	return highlighter.codeToHtml(normalizeCodeForHighlight(value, language), {
		lang: language,
		theme: 'github-light'
	});
};

const toJsonLiteral = (value: string): string | null => {
	if (!isJsonBlock(value)) return null;
	return JSON.stringify(JSON.parse(value), null, 2);
};

const splitTopLevelMembers = (value: string): string[] => {
	const members: string[] = [];
	let current = '';
	let depth = 0;
	let inSingleQuote = false;
	let inDoubleQuote = false;
	let escaped = false;

	for (let index = 0; index < value.length; index += 1) {
		const ch = value[index];

		if (escaped) {
			current += ch;
			escaped = false;
			continue;
		}

		if (ch === '\\\\') {
			current += ch;
			escaped = true;
			continue;
		}

		if (inSingleQuote) {
			current += ch;
			if (ch === "'") inSingleQuote = false;
			continue;
		}

		if (inDoubleQuote) {
			current += ch;
			if (ch === '"') inDoubleQuote = false;
			continue;
		}

		if (ch === "'") {
			inSingleQuote = true;
			current += ch;
			continue;
		}

		if (ch === '"') {
			inDoubleQuote = true;
			current += ch;
			continue;
		}

		if (ch === '{' || ch === '[' || ch === '(') {
			depth += 1;
			current += ch;
			continue;
		}

		if (ch === '}' || ch === ']' || ch === ')') {
			depth = Math.max(0, depth - 1);
			current += ch;
			continue;
		}

		if (ch === ',' && depth === 0) {
			if (current.trim()) members.push(current.trim());
			current = '';
			continue;
		}

		current += ch;
	}

	if (current.trim()) members.push(current.trim());
	return members;
};

const findTopLevelColon = (value: string): number => {
	let depth = 0;
	let inSingleQuote = false;
	let inDoubleQuote = false;
	let escaped = false;

	for (let index = 0; index < value.length; index += 1) {
		const ch = value[index];

		if (escaped) {
			escaped = false;
			continue;
		}

		if (ch === '\\\\') {
			escaped = true;
			continue;
		}

		if (inSingleQuote) {
			if (ch === "'") inSingleQuote = false;
			continue;
		}

		if (inDoubleQuote) {
			if (ch === '"') inDoubleQuote = false;
			continue;
		}

		if (ch === "'") {
			inSingleQuote = true;
			continue;
		}

		if (ch === '"') {
			inDoubleQuote = true;
			continue;
		}

		if (ch === '{' || ch === '[' || ch === '(') {
			depth += 1;
			continue;
		}

		if (ch === '}' || ch === ']' || ch === ')') {
			depth = Math.max(0, depth - 1);
			continue;
		}

		if (ch === ':' && depth === 0) {
			return index;
		}
	}

	return -1;
};

const isQuotedLiteral = (value: string): boolean => {
	return (
		(value.startsWith('"') && value.endsWith('"')) ||
		(value.startsWith("'") && value.endsWith("'")) ||
		(value.startsWith('\`') && value.endsWith('\`'))
	);
};

const toFetchScalarLiteral = (value: string): string => {
	const trimmed = value.trim();
	if (!trimmed) return "''";
	if (isQuotedLiteral(trimmed)) return trimmed;
	if (/^-?\\d+(?:\\.\\d+)?(?:[eE][+\\-]?\\d+)?$/.test(trimmed)) return trimmed;
	if (/^(true|false|null|undefined)$/u.test(trimmed)) return trimmed;
	return JSON.stringify(trimmed);
};

const toFetchObjectLiteral = (value: string): string | null => {
	if (!isTypeObject(value)) return null;

	const inner = value.trim().slice(1, -1).trim();
	if (!inner) return '{}';

	const members = splitTopLevelMembers(inner)
		.map((member) => {
			const colonIndex = findTopLevelColon(member);
			if (colonIndex < 0) return null;

			const rawKey = member.slice(0, colonIndex).trim().replace(/\\?$/u, '');
			const rawValue = member.slice(colonIndex + 1).trim();
			if (!rawKey || !rawValue) return null;

			const key = /^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(rawKey) ? rawKey : JSON.stringify(rawKey);
			const valueLiteral = toFetchValueLiteral(rawValue);
			return key + ': ' + valueLiteral;
		})
		.filter((member): member is string => Boolean(member));

	if (members.length === 0) return '{}';
	return '{\\n  ' + members.join(',\\n  ') + '\\n}';
};

const toFetchValueLiteral = (value: string): string => {
	const jsonLiteral = toJsonLiteral(value);
	if (jsonLiteral) return jsonLiteral;

	const objectLiteral = toFetchObjectLiteral(value);
	if (objectLiteral) return objectLiteral;

	return toFetchScalarLiteral(value);
};

const toFetchHeadersLiteral = (value: string): string => {
	return toFetchValueLiteral(value);
};

const toFetchBodyLiteral = (value: string): string => {
	const jsonLiteral = toJsonLiteral(value);
	if (jsonLiteral) return 'JSON.stringify(' + jsonLiteral + ', null, 2)';

	const objectLiteral = toFetchObjectLiteral(value);
	if (objectLiteral) return 'JSON.stringify(' + objectLiteral + ', null, 2)';

	return JSON.stringify(value);
};

const escapeRegExp = (value: string): string => value.replace(/[\\^$.*+?()[\]{}|]/g, '\\$&');

const extractParamName = (value: string): string | null => {
	const trimmed = value.trim();
	if (!trimmed) return null;
	const match = trimmed.match(/^(\S+)/u);
	const rawName = match?.[1]?.trim() ?? '';
	return rawName ? rawName.replace(/[?:]+$/u, '') : null;
};

const routePathFromTag = (value: string): string => {
	const trimmed = value.trim();
	if (!trimmed) return '';
	const match = trimmed.match(/^(?:[A-Z]+\s+)?(.+)$/u);
	return match?.[1]?.trim() ?? trimmed;
};

const buildFetchUrl = (doc: (typeof docs)[number]): string => {
	const paramNames = doc.params
		.map((param) => extractParamName(param.value))
		.filter((name): name is string => Boolean(name));
	const routeTag = doc.tags.find((tag) => tag.name.toLowerCase() === 'route');
	const configuredUrl = doc.fetchUrl.trim() || routePathFromTag(routeTag?.value ?? '') || 'https://api.example.com/endpoint';
	let url = configuredUrl;
	let usedTemplate = false;

	for (const paramName of paramNames) {
		const placeholderValue = '<' + paramName + '>';
		const escapedName = escapeRegExp(paramName);
		const curlyPattern = new RegExp('\\\\{' + escapedName + '\\\\}', 'g');
		const colonPattern = new RegExp(':' + escapedName + '(?=\\\\b|/|$)', 'g');
		if (curlyPattern.test(url) || colonPattern.test(url)) {
			url = url.replace(curlyPattern, placeholderValue).replace(colonPattern, placeholderValue);
			usedTemplate = true;
		}
	}

	if (!usedTemplate && paramNames.length > 0) {
		const suffix = paramNames.map((paramName) => '<' + paramName + '>').join('/');
		url = url.replace(/\\/+$/u, '') + '/' + suffix;
	}

	return url;
};

const buildAutoFetchExample = (doc: (typeof docs)[number]): { key: string; label: string; content: string } | null => {
	const methodTag = doc.tags.find((tag) => tag.name.toLowerCase() === 'method');
	const methodValue = methodTag?.value.trim().toUpperCase();
	if (!methodValue) return null;
	const fetchUrl = buildFetchUrl(doc);

	const requestLines = ["method: '" + methodValue + "'"];
	if (doc.headers) {
		requestLines.push('headers: ' + toFetchHeadersLiteral(doc.headers));
	}
	if (doc.body) {
		requestLines.push('body: ' + toFetchBodyLiteral(doc.body));
	}

	const indentedRequest = requestLines
		.map((line) => line.split('\\n').map((segment) => '  ' + segment).join('\\n'))
		.join(',\\n');

	return {
		key: 'generated-fetch',
		label: 'Fetch example',
		content:
			'const response = await fetch(' + JSON.stringify(fetchUrl) + ', {\\n' +
			indentedRequest +
			"\\n});\\n\\nconst data = await response.json();\\nconsole.log(data);"
	};
};

/** Resolves a single docs entry by slug for the detail page. */
export const load: PageServerLoad = async ({ params }) => {
	const doc = docs.find((entry) => entry.slug === params.slug);
	if (!doc) {
		throw error(404, 'Documentation entry not found');
	}

	const authorTag = doc.tags.find((tag) => tag.name.toLowerCase() === 'author');
	const resolvedAuthor = authorTag ? resolveAuthor(authorTag.value) : null;
	const inferredResponse = doc.response ? null : extractJsonBlock(doc.description);
	const docDescription = inferredResponse ? inferredResponse.remainder : doc.description;
	const responseValue = doc.response || inferredResponse?.value || '';
	const rawExamples = [
		...(() => {
			const generatedExample = buildAutoFetchExample(doc);
			return generatedExample ? [generatedExample] : [];
		})(),
		...doc.examples.map((example, index) => splitExampleContent(example, index))
	];
	const highlightedExamples: HighlightedExample[] = await Promise.all(
		rawExamples.map(async (example) => ({
			key: example.key,
			label: example.label,
			html: await highlightCode(example.content, example.language)
		}))
	);

	return {
		doc,
		author: resolvedAuthor?.profile ?? null,
		authorKey: resolvedAuthor?.key ?? null,
		docDescription,
		responseValue,
		highlighted: {
			signature: doc.signature ? await highlightCode(doc.signature, languageFromFilePath(doc.filePath)) : null,
			headers: doc.headers ? await highlightCode(doc.headers, 'json') : null,
			body: doc.body ? await highlightCode(doc.body, 'json') : null,
			returns:
				doc.returns && (isJsonBlock(doc.returns) || isTypeObject(doc.returns))
					? await highlightCode(doc.returns, 'typescript')
					: null,
			response: responseValue ? await highlightCode(responseValue, 'json') : null,
			examples: highlightedExamples
		}
	};
};
`;
};

/**
 * @auto-doc
 * @title Docs Detail Page Emitter
 * @group Output
 * Produces generated UI source for `/docs/[slug]/+page.svelte`.
 * @returns Svelte source for docs detail with author card and contrast-safe light mode.
 */
export const createDocsSlugPageSvelteModule = (collapseJson = false): string => {
	const collapseJsonLiteral = collapseJson ? 'true' : 'false';
	return `<script lang="ts">
	import { resolve } from '$app/paths';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();

	const currentIndex = $derived(data.docs.findIndex((entry) => entry.slug === data.doc.slug));
	const prevDoc = $derived(currentIndex > 0 ? data.docs[currentIndex - 1] : null);
	const nextDoc = $derived(
		currentIndex >= 0 && currentIndex < data.docs.length - 1 ? data.docs[currentIndex + 1] : null
	);
	const methodTag = $derived(
		data.doc.tags.find((tag) => tag.name.toLowerCase() === 'method') ?? null
	);
	const docDescription = $derived(data.docDescription || data.doc.description);
	const responseValue = $derived(data.responseValue || data.doc.response || '');
	const headersValue = $derived(data.doc.headers || '');
	const bodyValue = $derived(data.doc.body || '');
	const nonAuthorTags = $derived(
		data.doc.tags.filter((tag) => {
			const normalized = tag.name.toLowerCase();
			return normalized !== 'author' && normalized !== 'method' && normalized !== 'headers' && normalized !== 'body' && normalized !== 'fetchurl' && normalized !== 'fetch-url';
		})
	);
	const formattedLastModified = $derived(
		new Date(data.doc.lastModified).toLocaleString(undefined, {
			year: 'numeric',
			month: 'short',
			day: '2-digit',
			hour: '2-digit',
			minute: '2-digit'
		})
	);
	const docGroup = $derived(data.doc.group || 'Ungrouped');
	const docGroupSegments = $derived(
		docGroup
			.split('/')
			.map((segment) => segment.trim())
			.filter(Boolean)
	);
	const docGroupCrumbs = $derived(
		docGroupSegments.map((segment, index) => ({
			label: segment,
			path: docGroupSegments.slice(0, index + 1).join('/')
		}))
	);
	const groupHref = (groupPath: string): string =>
		'/docs/groups/' +
		groupPath
			.split('/')
			.map((segment) => encodeURIComponent(segment))
			.join('/');
	const collapseJson = ${collapseJsonLiteral};

	const methodTone = (tag: { name: string; value: string }): { pill: string; code: string; value: string } => {
		if (tag.name.toLowerCase() !== 'method') {
			return {
				pill: 'border-zinc-200 bg-zinc-50 text-zinc-950',
				code: 'border-cyan-300 bg-cyan-100 text-cyan-800',
				value: 'text-zinc-950'
			};
		}

		switch (tag.value.trim().toUpperCase()) {
			case 'POST':
				return {
					pill: 'border-blue-300 bg-blue-50 text-blue-900',
					code: 'border-blue-300 bg-blue-100 text-blue-800',
					value: 'text-blue-900 font-semibold'
				};
			case 'PUT':
				return {
					pill: 'border-orange-300 bg-orange-50 text-orange-950',
					code: 'border-orange-300 bg-orange-100 text-orange-900',
					value: 'text-orange-950 font-semibold'
				};
				case 'PATCH':
					return {
						pill: 'border-amber-300 bg-amber-50 text-amber-900',
						code: 'border-amber-300 bg-amber-100 text-amber-800',
						value: 'text-amber-900 font-semibold'
					};
			case 'DELETE':
				return {
					pill: 'border-rose-300 bg-rose-50 text-rose-900',
					code: 'border-rose-300 bg-rose-100 text-rose-800',
					value: 'text-rose-900 font-semibold'
				};
			case 'GET':
				return {
					pill: 'border-emerald-300 bg-emerald-50 text-emerald-900',
					code: 'border-emerald-300 bg-emerald-100 text-emerald-800',
					value: 'text-emerald-900 font-semibold'
				};
			default:
				return {
					pill: 'border-zinc-200 bg-zinc-50 text-zinc-950',
					code: 'border-cyan-300 bg-cyan-100 text-cyan-800',
					value: 'text-zinc-950'
				};
		}
	};

	const escapeHtml = (value: string): string =>
		value
			.replaceAll('&', '&amp;')
			.replaceAll('<', '&lt;')
			.replaceAll('>', '&gt;')
			.replaceAll('"', '&quot;')
			.replaceAll("'", '&#39;');

	const isJsonBlock = (value: string): boolean => {
		const trimmed = value.trim();
		if (!trimmed) return false;
		if (!((trimmed.startsWith('{') && trimmed.endsWith('}')) || (trimmed.startsWith('[') && trimmed.endsWith(']')))) {
			return false;
		}

		try {
			JSON.parse(trimmed);
			return true;
		} catch {
			return false;
		}
	};

	const highlightJson = (value: string): string => {
		const parsed = JSON.parse(value) as unknown;
		const pretty = collapseJson ? JSON.stringify(parsed) : JSON.stringify(parsed, null, 2);

		const highlightScalars = (line: string): string =>
			line
				.replace(/&quot;([^&]*)&quot;/g, '<span class="text-emerald-700">&quot;$1&quot;</span>')
				.replace(/\\b(true|false|null)\\b/g, '<span class="text-violet-700">$1</span>')
				.replace(/-?\\d+(?:\\.\\d+)?(?:[eE][+\\-]?\\d+)?/g, '<span class="text-amber-700">$&</span>');

		if (collapseJson) {
			const escaped = escapeHtml(pretty);
			const withKeys = escaped.replace(
				/(&quot;([^&]*)&quot;)(\\s*:)/g,
				'<span class="text-blue-700">$1</span>$3'
			);
			return highlightScalars(withKeys);
		}

		return pretty
			.split(String.fromCharCode(10))
			.map((rawLine) => {
				const escapedLine = escapeHtml(rawLine);
				const keyMatch = escapedLine.match(/^(\\s*)&quot;([^&]*)&quot;:\\s*(.*)$/);
				if (!keyMatch) return highlightScalars(escapedLine);

				const indent = keyMatch[1];
				const key = keyMatch[2];
				const rest = keyMatch[3];
				return (
					indent +
					'<span class="text-blue-700">&quot;' +
					key +
					'&quot;</span>: ' +
					highlightScalars(rest)
				);
			})
			.join('<br />');
	};

	const isTypeObject = (value: string): boolean => {
		const trimmed = value.trim();
		return trimmed.startsWith('{') && trimmed.endsWith('}');
	};

	const formatTypeObject = (value: string, collapsed: boolean): string => {
		const source = value.trim();
		if (!source) return '';

		const indentUnit = '  ';
		let out = '';
		let depth = 0;
		let inSingleQuote = false;
		let inDoubleQuote = false;
		let escaped = false;

		const isWhitespace = (ch: string): boolean => ch === ' ' || ch === '\\n' || ch === '\\r' || ch === '\\t';
		const appendIndent = (count: number): void => {
			if (count <= 0) return;
			out += indentUnit.repeat(count);
		};
		const nextNonWhitespace = (start: number): string => {
			for (let i = start; i < source.length; i += 1) {
				const ch = source[i];
				if (!isWhitespace(ch)) return ch;
			}
			return '';
		};

		for (let i = 0; i < source.length; i += 1) {
			const ch = source[i];

			if (inSingleQuote || inDoubleQuote) {
				out += ch;
				if (escaped) {
					escaped = false;
					continue;
				}
				if (ch === '\\\\') {
					escaped = true;
					continue;
				}
				if (inSingleQuote && ch === "'") {
					inSingleQuote = false;
				} else if (inDoubleQuote && ch === '"') {
					inDoubleQuote = false;
				}
				continue;
			}

			if (ch === "'") {
				inSingleQuote = true;
				out += ch;
				continue;
			}

			if (ch === '"') {
				inDoubleQuote = true;
				out += ch;
				continue;
			}

			if (collapsed) {
				if (isWhitespace(ch)) {
					if (out.length > 0 && out[out.length - 1] !== ' ') out += ' ';
					continue;
				}
				out += ch;
				continue;
			}

			if (isWhitespace(ch)) {
				if (out.endsWith('\\n')) continue;
				if (!out.endsWith(' ')) out += ' ';
				continue;
			}

			if (ch === '{' || ch === '[') {
				out += ch;
				depth += 1;
				const closing = ch === '{' ? '}' : ']';
				if (nextNonWhitespace(i + 1) !== closing) {
					out += '\\n';
					appendIndent(depth);
				}
				continue;
			}

			if (ch === '}' || ch === ']') {
				depth = Math.max(0, depth - 1);
				while (out.endsWith(' ')) out = out.slice(0, -1);
				if (!out.endsWith('\\n') && out.length > 0) {
					out += '\\n';
				}
				appendIndent(depth);
				out += ch;
				continue;
			}

			if (ch === ',') {
				out += ',\\n';
				appendIndent(depth);
				continue;
			}

			if (ch === ':') {
				while (out.endsWith(' ')) out = out.slice(0, -1);
				out += ': ';
				continue;
			}

			if (ch === '|') {
				while (out.endsWith(' ')) out = out.slice(0, -1);
				out += ' | ';
				continue;
			}

			out += ch;
		}

		return out.trim();
	};

	const highlightTypeObject = (value: string): string => {
		const escaped = escapeHtml(value);
		const withKeys = escaped.replace(
			/(^|[,{]\\s*)([A-Za-z_][A-Za-z0-9_]*)(\\?)?\\s*:/g,
			'$1<span class="text-blue-700">$2</span><span class="text-rose-700">$3</span>:'
		);
		const withTypes = withKeys.replace(
			/\\b(string|number|boolean|object|unknown|any|never|void|null|undefined|Date|Record|Array)\\b/g,
			'<span class="text-emerald-700">$1</span>'
		);
		const withPipes = withTypes.replace(/\\|/g, '<span class="text-violet-700">|</span>');
		const withPunctuation = withPipes.replace(/([{}()[\\],:])/g, '<span class="text-zinc-500">$1</span>');
		return withPunctuation.replace(/\\n/g, '<br />');
	};

	const renderResponse = (value: string): string =>
		isJsonBlock(value)
			? highlightJson(value)
			: isTypeObject(value)
				? highlightTypeObject(formatTypeObject(value, collapseJson))
				: escapeHtml(value).replace(/\\n/g, '<br />');

	const isStructuredValue = (value: string): boolean => isJsonBlock(value) || isTypeObject(value);

	const splitParamParts = (value: string): { argument: string; description: string } => {
		const trimmed = value.trim();
		if (!trimmed) return { argument: '', description: '' };

		const match = trimmed.match(/^(\S+)(?:\s+([\s\S]*))?$/);
		if (!match) return { argument: trimmed, description: '' };

		return {
			argument: match[1] ?? trimmed,
			description: (match[2] ?? '').trim()
		};
	};

	const renderStructuredValue = (value: string): string => renderResponse(value);

</script>

<div class="docs-detail mx-auto max-w-5xl">
	<div class="docs-detail-head border-b border-zinc-300 pb-4">
		<nav class="flex items-center gap-2 text-xs font-semibold tracking-wide uppercase" aria-label="Breadcrumb">
			<a href={resolve('/docs')} class="text-zinc-900 hover:text-cyan-700 docs-detail-link">All docs</a>
			{#each docGroupCrumbs as crumb (\`\${crumb.path}\`)}
				<span class="text-zinc-500">/</span>
				<a href={groupHref(crumb.path)} class="text-zinc-900 hover:text-cyan-700">{crumb.label}</a>
			{/each}
			<span class="text-zinc-500">/</span>
			<span class="text-zinc-700">{data.doc.title}</span>
		</nav>
	</div>

	<article
		class="docs-detail-surface border-x border-b border-zinc-300 bg-white p-6 sm:p-8"
	>
		<div>
			<div class="flex items-start justify-between gap-4">
				<div class="min-w-0 flex-1">
					<h1 class="docs-detail-title text-4xl font-black tracking-tight text-zinc-950">
						{data.doc.title}
					</h1>
					<p class="docs-detail-muted mt-2 text-[11px] text-zinc-700">
						{data.doc.displayPath ?? \`\${data.doc.filePath}:\${data.doc.line}\`}
					</p>
					{#if docDescription}
						<div class="mt-4 text-sm leading-relaxed text-zinc-950">
							<p>{docDescription}</p>
						</div>
					{/if}
				</div>
				{#if methodTag}
					{@const tone = methodTone(methodTag)}
					<div class={\`shrink-0 border px-3 py-1 text-xs \${tone.pill}\`}>
						<code class={\`mr-1 inline-block border px-1.5 py-0.5 font-semibold \${tone.code}\`}>@{methodTag.name}</code>
						<span class={tone.value}>{methodTag.value}</span>
					</div>
				{/if}
			</div>

			{#if nonAuthorTags.length > 0}
				<div class="mt-4 space-y-2">
					{#each nonAuthorTags as tag (\`\${tag.name}-\${tag.value}\`)}
						{@const tone = methodTone(tag)}
						{#if isStructuredValue(tag.value)}
							<div class="border border-zinc-200 bg-zinc-50 px-4 py-3 text-sm text-zinc-950">
								<div class={\`mb-2 inline-flex border px-3 py-1 text-xs \${tone.pill}\`}>
									<code class={\`mr-1 inline-block border px-1.5 py-0.5 font-semibold \${tone.code}\`}>@{tag.name}</code>
								</div>
								<pre class="overflow-x-auto text-xs text-zinc-950"><code>{@html renderStructuredValue(tag.value)}</code></pre>
							</div>
						{:else}
							<div class={\`border px-3 py-1 text-xs \${tone.pill}\`}>
								<code class={\`mr-1 inline-block border px-1.5 py-0.5 font-semibold \${tone.code}\`}>@{tag.name}</code>
								<span class={tone.value}>{tag.value}</span>
							</div>
						{/if}
					{/each}
				</div>
			{/if}

			{#if data.author}
				<section class="docs-author-panel mt-5 w-full border border-zinc-300 bg-zinc-50 p-2.5 sm:max-w-xs">
				<div class="flex items-center gap-2.5">
					{#if data.author.imageUrl}
						<img
							src={data.author.imageUrl}
							alt={data.author.name}
							class="h-8 w-8 rounded-full border border-zinc-300 object-cover"
						/>
					{/if}
					<div class="min-w-0 flex-1">
						<p
							class="text-[10px] font-semibold tracking-[0.18em] text-zinc-700 uppercase"
						>
							Author
						</p>
						<a href={resolve(\`/docs/authors/\${data.authorKey ?? data.author.username ?? ''}\`)} class="inline-block mt-0.5 text-sm font-bold text-zinc-900 hover:text-cyan-700">
							{data.author.name}
						</a>
						{#if data.author.title}
							<p class="mt-0.5 text-[11px] text-zinc-600">
								{data.author.title}
							</p>
						{/if}
					</div>
				</div>
				</section>
			{/if}
		</div>

		{#if data.doc.signature}
			{#if data.highlighted.signature}
				<div class="docs-highlight docs-signature-highlight mt-5 overflow-hidden rounded-sm border border-zinc-300">{@html data.highlighted.signature}</div>
			{:else}
				<pre
					class="docs-detail-code mt-5 max-h-128 overflow-auto border border-zinc-300 bg-zinc-100 p-4 text-xs text-zinc-950"><code
						>{data.doc.signature}</code
					></pre>
			{/if}
		{/if}

		{#if data.doc.params.length > 0}
			<section class="docs-detail-section mt-6 border-t border-zinc-200 pt-6">
				<h2
					class="text-[11px] font-bold tracking-[0.16em] text-zinc-900 uppercase"
				>
					Parameters
				</h2>
				<ul class="mt-3 space-y-2">
					{#each data.doc.params as param (\`\${param.name}-\${param.value}\`)}
						{@const paramParts = splitParamParts(param.value)}
						<li
							class="border border-zinc-200 bg-zinc-50 px-4 py-3 text-sm text-zinc-950"
						>
							<div class="flex items-start gap-4">
								<code class="shrink-0 inline-block border border-cyan-300 bg-cyan-100 px-1.5 py-0.5 font-semibold text-cyan-800">@{param.name}</code>
							{#if isStructuredValue(param.value)}
								<pre class="min-w-0 flex-1 overflow-x-auto text-xs text-zinc-950"><code>{@html renderStructuredValue(param.value)}</code></pre>
							{:else}
								<div class="min-w-0 flex-1">
									{#if paramParts.argument}
										<p class="font-mono text-base font-semibold text-zinc-950">{paramParts.argument}</p>
									{/if}
									{#if paramParts.description}
										<p class="mt-1 text-sm leading-relaxed text-zinc-600">{paramParts.description}</p>
									{/if}
								</div>
							{/if}
							</div>
						</li>
					{/each}
				</ul>
			</section>
		{/if}

		{#if headersValue}
			<section class="docs-detail-section mt-8 border-t border-zinc-200 pt-6">
				<h2 class="text-[11px] font-bold tracking-[0.16em] text-zinc-900 uppercase">Headers</h2>
				{#if data.highlighted.headers}
					<div class="docs-highlight mt-3 overflow-hidden rounded-sm border border-zinc-200">{@html data.highlighted.headers}</div>
				{:else}
					<pre class="mt-3 overflow-x-auto border border-zinc-200 bg-zinc-50 px-4 py-3 text-xs text-zinc-950"><code>{@html renderStructuredValue(headersValue)}</code></pre>
				{/if}
			</section>
		{/if}

		{#if bodyValue}
			<section class="docs-detail-section mt-8 border-t border-zinc-200 pt-6">
				<h2 class="text-[11px] font-bold tracking-[0.16em] text-zinc-900 uppercase">Body</h2>
				{#if data.highlighted.body}
					<div class="docs-highlight mt-3 overflow-hidden rounded-sm border border-zinc-200">{@html data.highlighted.body}</div>
				{:else}
					<pre class="mt-3 overflow-x-auto border border-zinc-200 bg-zinc-50 px-4 py-3 text-xs text-zinc-950"><code>{@html renderStructuredValue(bodyValue)}</code></pre>
				{/if}
			</section>
		{/if}

		{#if data.highlighted.examples.length > 0}
			<section class="docs-detail-section mt-8 border-t border-zinc-200 pt-6">
				<h2
					class="text-[11px] font-bold tracking-[0.16em] text-zinc-900 uppercase"
				>
					Examples
				</h2>
				<div class="mt-3 space-y-3">
					{#each data.highlighted.examples as example (example.key)}
						{#if example.label}
							<p class="text-[10px] font-semibold tracking-[0.18em] text-zinc-700 uppercase">{example.label}</p>
						{/if}
						<div class="docs-highlight overflow-hidden rounded-sm border border-zinc-200">{@html example.html}</div>
					{/each}
				</div>
			</section>
		{/if}

		{#if data.doc.returns}
			<section class="docs-detail-section mt-8 border-t border-zinc-200 pt-6">
				<h2
					class="text-[11px] font-bold tracking-[0.16em] text-zinc-900 uppercase"
				>
					Returns
				</h2>
				{#if data.highlighted.returns}
					<div class="docs-highlight mt-3 overflow-hidden rounded-sm border border-zinc-200">{@html data.highlighted.returns}</div>
					<pre class="mt-3 overflow-x-auto border border-zinc-200 bg-zinc-50 px-4 py-3 text-xs text-zinc-950"><code>{@html renderStructuredValue(data.doc.returns)}</code></pre>
				{:else}
					<p
						class="mt-3 border border-zinc-200 bg-zinc-50 px-4 py-3 text-sm text-zinc-950"
					>
						{data.doc.returns}
					</p>
				{/if}
			</section>
		{/if}

		{#if responseValue}
			<section class="docs-detail-section mt-8 border-t border-zinc-200 pt-6">
				<h2
					class="text-[11px] font-bold tracking-[0.16em] text-zinc-900 uppercase"
				>
					Response
				</h2>
				{#if data.highlighted.response}
					<div class="docs-highlight mt-3 overflow-hidden rounded-sm border border-zinc-200">{@html data.highlighted.response}</div>
				{:else}
					<pre class="mt-3 overflow-x-auto border border-zinc-200 bg-zinc-50 px-4 py-3 text-xs text-zinc-950"><code>{@html renderStructuredValue(responseValue)}</code></pre>
				{/if}
			</section>
		{/if}

		<section class="docs-detail-section mt-8 border-t border-zinc-200 pt-5">
			<h2 class="text-[11px] font-bold tracking-[0.16em] text-zinc-900 uppercase">History</h2>
			<p class="mt-2 text-sm text-zinc-800">Last modified: <span class="font-semibold">{formattedLastModified}</span></p>
			{#if data.doc.versionHistory.length > 0}
				<ul class="mt-3 flex flex-wrap gap-2">
					{#each data.doc.versionHistory as version, index (\`\${version}\`)}
						<li>
							<a
								href={resolve(\`/docs/\${data.doc.slug}/versions/\${version}\`)}
								class="block border border-zinc-200 bg-zinc-50 px-2.5 py-1 text-xs font-semibold text-zinc-900 hover:border-cyan-500 hover:text-cyan-700"
							>
								{version}{index === 0 ? ' (latest)' : ''}
							</a>
						</li>
					{/each}
				</ul>
			{/if}
		</section>

		<div class="docs-detail-section mt-10 grid gap-3 border-t border-zinc-200 pt-5 sm:grid-cols-2">
			{#if prevDoc}
				<a
					href={resolve(\`/docs/\${prevDoc.slug}\`)}
					class="border border-zinc-300 bg-zinc-100 px-4 py-3 text-xs text-zinc-950 hover:border-cyan-500 hover:text-cyan-700"
				>
					<p class="font-semibold tracking-wide uppercase">Previous</p>
					<p class="mt-1 truncate text-sm text-zinc-950">{prevDoc.title}</p>
				</a>
			{/if}
			{#if nextDoc}
				<a
					href={resolve(\`/docs/\${nextDoc.slug}\`)}
					class={\`border border-zinc-300 bg-zinc-100 px-4 py-3 text-xs text-zinc-950 hover:border-cyan-500 hover:text-cyan-700 \${prevDoc ? '' : 'sm:col-start-2'}\`}
				>
					<p class="font-semibold tracking-wide uppercase">Next</p>
					<p class="mt-1 truncate text-sm text-zinc-950">{nextDoc.title}</p>
				</a>
			{/if}
		</div>
	</article>
</div>

<style>
	:global(.docs-highlight pre.shiki) {
		margin: 0;
		padding: 1rem;
		overflow-x: auto;
		font-size: 0.75rem;
		line-height: 1.6;
	}

	:global(.docs-signature-highlight pre.shiki) {
		max-height: 32rem;
		overflow: auto;
	}

	:global(.docs-highlight pre.shiki code) {
		font-family: 'IBM Plex Mono', 'SFMono-Regular', ui-monospace, Menlo, monospace;
	}
</style>
`;
};

/**
 * @auto-doc
 * @title Version Detail Load Emitter
 * @group Output
 * Produces generated load logic for `/docs/[slug]/versions/[version]/+page.ts`.
 * @returns TypeScript source for selected version diff data.
 */
export const createDocsVersionPageTsModule = (): string => {
	return `import { error } from '@sveltejs/kit';
import type { PageLoad } from './$types';
import { docs, history } from '../../../generated';

type DiffLine = {
	kind: 'context' | 'add' | 'remove';
	text: string;
};

const buildUnifiedDiff = (beforeText: string, afterText: string): DiffLine[] => {
	const before = beforeText.split(/\\r?\\n/);
	const after = afterText.split(/\\r?\\n/);
	const dp = Array.from({ length: before.length + 1 }, () => Array(after.length + 1).fill(0));

	for (let i = before.length - 1; i >= 0; i -= 1) {
		for (let j = after.length - 1; j >= 0; j -= 1) {
			dp[i][j] = before[i] === after[j] ? dp[i + 1][j + 1] + 1 : Math.max(dp[i + 1][j], dp[i][j + 1]);
		}
	}

	const result: DiffLine[] = [];
	let i = 0;
	let j = 0;

	while (i < before.length && j < after.length) {
		if (before[i] === after[j]) {
			result.push({ kind: 'context', text: before[i] });
			i += 1;
			j += 1;
			continue;
		}

		if (dp[i + 1][j] >= dp[i][j + 1]) {
			result.push({ kind: 'remove', text: before[i] });
			i += 1;
		} else {
			result.push({ kind: 'add', text: after[j] });
			j += 1;
		}
	}

	while (i < before.length) {
		result.push({ kind: 'remove', text: before[i] });
		i += 1;
	}

	while (j < after.length) {
		result.push({ kind: 'add', text: after[j] });
		j += 1;
	}

	return result;
};

/** Loads selected version data and computes field-level change details against the prior version. */
export const load: PageLoad = async ({ params }) => {
	const doc = docs.find((entry) => entry.slug === params.slug);
	if (!doc) {
		throw error(404, 'Documentation entry not found');
	}

	const versions = history[doc.id] ?? [];
	const index = versions.findIndex((entry) => entry.version === params.version);
	if (index < 0) {
		throw error(404, 'Version not found for this documentation entry');
	}

	const selectedVersion = versions[index];
	const priorVersion = index + 1 < versions.length ? versions[index + 1] : null;

	const beforeRaw = priorVersion?.snapshot.jsdocRaw ?? '';
	const afterRaw = selectedVersion.snapshot.jsdocRaw ?? '';
	const diffLines = buildUnifiedDiff(beforeRaw, afterRaw);
	const hasDiff = diffLines.some((line) => line.kind !== 'context');

	return {
		doc,
		selectedVersion,
		priorVersion,
		diffLines,
		hasDiff
	};
};
`;
};

/**
 * @auto-doc
 * @title Version Detail Page Emitter
 * @group Output
 * Produces generated UI source for `/docs/[slug]/versions/[version]/+page.svelte`.
 * @returns Svelte source for a "what changed" version details page.
 */
export const createDocsVersionPageSvelteModule = (): string => {
	return `<script lang="ts">
	import { resolve } from '$app/paths';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();
	const changedAt = $derived(new Date(data.selectedVersion.changedAt).toLocaleString());
	const docGroup = $derived(data.doc.group || 'Ungrouped');
	const docGroupSegments = $derived(
		docGroup
			.split('/')
			.map((segment) => segment.trim())
			.filter(Boolean)
	);
	const docGroupCrumbs = $derived(
		docGroupSegments.map((segment, index) => ({
			label: segment,
			path: docGroupSegments.slice(0, index + 1).join('/')
		}))
	);
	const groupHref = (groupPath: string): string =>
		'/docs/groups/' +
		groupPath
			.split('/')
			.map((segment) => encodeURIComponent(segment))
			.join('/');
</script>

<div class="docs-version mx-auto max-w-5xl">
	<div class="flex items-center justify-between border-b border-zinc-300 pb-4">
		<nav class="flex items-center gap-2 text-xs font-semibold tracking-wide uppercase" aria-label="Breadcrumb">
			<a href={resolve('/docs')} class="text-zinc-900 hover:text-cyan-700">All docs</a>
			{#each docGroupCrumbs as crumb (\`\${crumb.path}\`)}
				<span class="text-zinc-500">/</span>
				<a href={groupHref(crumb.path)} class="text-zinc-900 hover:text-cyan-700">{crumb.label}</a>
			{/each}
			<span class="text-zinc-500">/</span>
			<a href={resolve(\`/docs/\${data.doc.slug}\`)} class="text-zinc-900 hover:text-cyan-700">{data.doc.title}</a>
			<span class="text-zinc-500">/</span>
			<span class="text-zinc-700">{data.selectedVersion.version}</span>
		</nav>
		<p class="text-[11px] text-zinc-700">Version history</p>
	</div>

	<article class="mt-4 border border-zinc-300 bg-white p-6 sm:p-8">
		<p class="text-[10px] font-semibold tracking-[0.2em] text-cyan-700 uppercase">What changed</p>
		<h1 class="mt-2 text-3xl font-black tracking-tight text-zinc-950">{data.doc.title} - {data.selectedVersion.version}</h1>
		<p class="mt-2 text-sm text-zinc-800">Captured: <span class="font-semibold">{changedAt}</span></p>

		{#if data.priorVersion}
			<p class="mt-2 text-xs text-zinc-700">Compared to previous version <span class="font-semibold">{data.priorVersion.version}</span></p>
		{:else}
			<p class="mt-2 text-xs text-zinc-700">This is the first recorded version for this doc entry.</p>
		{/if}

		{#if !data.hasDiff}
			<div class="mt-6 border border-dashed border-zinc-300 bg-zinc-50 px-4 py-4 text-sm text-zinc-800">
				No changes detected
			</div>
		{:else}
			<div class="mt-6 overflow-x-auto border border-zinc-300 bg-zinc-950 text-zinc-100">
				<pre class="min-w-full px-0 py-0 text-xs"><code>{#each data.diffLines as line, idx (\`\${idx}-\${line.kind}\`)}<span class={line.kind === 'add' ? 'block bg-emerald-900/35 text-emerald-200' : line.kind === 'remove' ? 'block bg-rose-900/35 text-rose-200' : 'block text-zinc-300'}>{line.kind === 'add' ? '+' : line.kind === 'remove' ? '-' : ' '}{line.text}</span>{/each}</code></pre>
			</div>
		{/if}
	</article>
</div>
`;
};

/**
 * @auto-doc
 * @title Author Profile Load Emitter
 * @group Output
 * Produces generated load logic for `/docs/authors/[authorKey]/+page.ts`.
 * @returns TypeScript source for author profile data loading.
 */
export const createDocsAuthorPageTsModule = (): string => {
	return `import { error } from '@sveltejs/kit';
import type { PageLoad } from './$types';
import { authors } from '../../generated';

/** Loads a configured author profile by key for detail rendering. */
export const load: PageLoad = async ({ params }) => {
	const requestedKey = params.authorKey;
	const resolvedKey =
		authors[requestedKey]
			? requestedKey
			: Object.keys(authors).find((key) => key.toLowerCase() === requestedKey.toLowerCase());

	const author = resolvedKey ? authors[resolvedKey] : undefined;
	if (!author) {
		throw error(404, 'Author not found');
	}

	return {
		authorKey: resolvedKey,
		author
	};
};
`;
};

/**
 * @auto-doc
 * @title Author Profile Page Emitter
 * @group Output
 * Produces generated UI source for `/docs/authors/[authorKey]/+page.svelte`.
 * @returns Svelte source for author profile page with conditional contact sections.
 */
export const createDocsAuthorPageSvelteModule = (): string => {
	return `<script lang="ts">
	import { resolve } from '$app/paths';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();
	const phoneEntries = $derived(data.author.phone ? Object.entries(data.author.phone).filter(([, value]) => Boolean(value)) : []);
	const authorImageSrc = $derived(
		data.author.imageUrl
			? /^(https?:\\/\\/|\\/)/.test(data.author.imageUrl)
				? data.author.imageUrl
				: '/' + data.author.imageUrl.replace(/^\\.\\/+/, '').replace(/^\\/+/, '')
			: null
	);
</script>

<div class="docs-author-profile mx-auto max-w-4xl">
	<div class="flex items-center justify-between border-b border-zinc-300 pb-4">
		<a href={resolve('/docs')} class="text-xs font-semibold tracking-wide text-zinc-900 uppercase hover:text-cyan-700">All docs</a>
		<p class="text-[11px] text-zinc-700">Author profile</p>
	</div>

	<article class="mt-4 border border-zinc-300 bg-white p-6 sm:p-8">
		<div class="flex items-start gap-4">
			{#if authorImageSrc}
				<img src={authorImageSrc} alt={data.author.name} class="h-16 w-16 rounded-full border border-zinc-300 object-cover" />
			{/if}
			<div class="min-w-0 flex-1">
				<h1 class="text-3xl font-black tracking-tight text-zinc-950">{data.author.name}</h1>
				{#if data.author.title}
					<p class="mt-1 text-sm text-zinc-800">{data.author.title}</p>
				{/if}
				<p class="mt-1 text-xs text-zinc-700">@{data.author.username ?? data.authorKey}</p>
			</div>
		</div>

		{#if data.author.bio}
			<section class="mt-6 border-t border-zinc-200 pt-5">
				<h2 class="text-[11px] font-bold tracking-[0.16em] text-zinc-900 uppercase">Bio</h2>
				<p class="mt-2 text-sm leading-relaxed text-zinc-900">{data.author.bio}</p>
			</section>
		{/if}

		{#if data.author.email || data.author.address || phoneEntries.length > 0 || data.author.links}
			<section class="mt-6 border-t border-zinc-200 pt-5">
				<h2 class="text-[11px] font-bold tracking-[0.16em] text-zinc-900 uppercase">Contact</h2>

				{#if data.author.email}
					<p class="mt-2 text-sm text-zinc-900">Email: <a href={\`mailto:\${data.author.email}\`} class="font-semibold hover:text-cyan-700">{data.author.email}</a></p>
				{/if}

				{#if data.author.address}
					<p class="mt-2 text-sm text-zinc-900">Address: {data.author.address}</p>
				{/if}

				{#if phoneEntries.length > 0}
					<ul class="mt-3 space-y-1">
						{#each phoneEntries as [label, number] (\`\${label}-\${number}\`)}
							<li class="text-sm text-zinc-900"><span class="font-semibold capitalize">{label}:</span> {number}</li>
						{/each}
					</ul>
				{/if}

				{#if data.author.links}
					<div class="mt-4 flex flex-wrap gap-2">
						{#each Object.entries(data.author.links) as [label, href] (\`\${label}-\${href}\`)}
							<a
								href={href}
								target="_blank"
								rel="noopener noreferrer"
								class="border border-zinc-300 bg-zinc-50 px-2.5 py-1 text-[11px] font-semibold tracking-wide text-zinc-900 uppercase hover:border-cyan-500 hover:text-cyan-700"
							>
								{label}
							</a>
						{/each}
					</div>
				{/if}
			</section>
		{/if}
	</article>
</div>

`;
};
