// This file is generated by jsAutoDocs. Do not edit manually.

export type GeneratedDocTag = {
	name: string;
	value: string;
};

export type GeneratedDocEntry = {
	id: string;
	slug: string;
	group: string;
	title: string;
	summary: string;
	description: string;
	jsdocRaw: string;
	signature: string;
	filePath: string;
	line: number;
	displayPath: string;
	params: GeneratedDocTag[];
	returns: string;
	response: string;
	examples: string[];
	tags: GeneratedDocTag[];
	lastModified: string;
	versionHistory: string[];
};

export type GeneratedDocSnapshot = Pick<
	GeneratedDocEntry,
	'group' | 'title' | 'summary' | 'description' | 'jsdocRaw' | 'signature' | 'displayPath' | 'params' | 'returns' | 'response' | 'examples' | 'tags'
>;

export type GeneratedDocVersionRecord = {
	version: string;
	changedAt: string;
	snapshot: GeneratedDocSnapshot;
};

export type GeneratedAuthorProfile = {
	name: string;
	title?: string;
	username?: string;
	bio?: string;
	imageUrl?: string;
	email?: string;
	address?: string;
	phone?: Partial<Record<'mobile' | 'office' | 'home' | 'other', string>>;
	links?: Record<string, string>;
};

export const generatedAt = "2026-04-16T13:08:43.542Z";

export const docs: GeneratedDocEntry[] = [];

export const authors: Record<string, GeneratedAuthorProfile> = {};

export const history: Record<string, GeneratedDocVersionRecord[]> = {};
