// This file is generated by jsAutoDocs. Do not edit manually.

export type GeneratedDocTag = {
	name: string;
	value: string;
};

export type GeneratedDocEntry = {
	id: string;
	slug: string;
	group: string;
	title: string;
	summary: string;
	description: string;
	jsdocRaw: string;
	signature: string;
	filePath: string;
	line: number;
	displayPath: string;
	params: GeneratedDocTag[];
	returns: string;
	response: string;
	examples: string[];
	tags: GeneratedDocTag[];
	lastModified: string;
	versionHistory: string[];
};

export type GeneratedDocSnapshot = Pick<
	GeneratedDocEntry,
	'group' | 'title' | 'summary' | 'description' | 'jsdocRaw' | 'signature' | 'displayPath' | 'params' | 'returns' | 'response' | 'examples' | 'tags'
>;

export type GeneratedDocVersionRecord = {
	version: string;
	changedAt: string;
	snapshot: GeneratedDocSnapshot;
};

export type GeneratedAuthorProfile = {
	name: string;
	title?: string;
	username?: string;
	bio?: string;
	imageUrl?: string;
	email?: string;
	address?: string;
	phone?: Partial<Record<'mobile' | 'office' | 'home' | 'other', string>>;
	links?: Record<string, string>;
};

export const generatedAt = "2026-04-16T12:16:24.655Z";

export const docs: GeneratedDocEntry[] = [
  {
    "id": "src/lib/plugin-internals/discovery.ts:5",
    "slug": "source-file-walker-5",
    "group": "File Discovery",
    "title": "Source File Walker",
    "summary": "Recursively walks the scan directory and collects source files matching configured extensions.",
    "description": "Recursively walks the scan directory and collects source files matching configured extensions.\nSkips ignored system/build directories and the generated output file itself.",
    "jsdocRaw": "/**\n * @auto-doc\n * @title Source File Walker\n * @group File Discovery\n * Recursively walks the scan directory and collects source files matching configured extensions.\n * Skips ignored system/build directories and the generated output file itself.\n * @param dir Current directory being traversed.\n * @param extensions Allowed file extensions.\n * @param outputFilePath Absolute path of the generated docs output file.\n * @returns A flat list of absolute source file paths.\n */",
    "signature": "export const walk = async (",
    "filePath": "src/lib/plugin-internals/discovery.ts",
    "line": 5,
    "displayPath": "src/lib/plugin-internals/discovery.ts:5",
    "params": [
      {
        "name": "param",
        "value": "dir Current directory being traversed."
      },
      {
        "name": "param",
        "value": "extensions Allowed file extensions."
      },
      {
        "name": "param",
        "value": "outputFilePath Absolute path of the generated docs output file."
      }
    ],
    "returns": "A flat list of absolute source file paths.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/lib/plugin-internals/helpers.ts:1",
    "slug": "path-normalizer-1",
    "group": "Plugin Internals",
    "title": "Path Normalizer",
    "summary": "Normalizes file separators for stable cross-platform path keys.",
    "description": "Normalizes file separators for stable cross-platform path keys.",
    "jsdocRaw": "/**\n * @auto-doc\n * @title Path Normalizer\n * @group Plugin Internals\n * Normalizes file separators for stable cross-platform path keys.\n * @param value Input path value that may include platform-specific separators.\n * @returns A slash-normalized path string.\n */",
    "signature": "export const normalize = (value: string): string => value.replaceAll('\\\\', '/');",
    "filePath": "src/lib/plugin-internals/helpers.ts",
    "line": 1,
    "displayPath": "src/lib/plugin-internals/helpers.ts:1",
    "params": [
      {
        "name": "param",
        "value": "value Input path value that may include platform-specific separators."
      }
    ],
    "returns": "A slash-normalized path string.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/lib/plugin-internals/helpers.ts:11",
    "slug": "slug-generator-11",
    "group": "Plugin Internals",
    "title": "Slug Generator",
    "summary": "Creates a URL-safe slug from human-readable text.",
    "description": "Creates a URL-safe slug from human-readable text.",
    "jsdocRaw": "/**\n * @auto-doc\n * @title Slug Generator\n * @group Plugin Internals\n * Creates a URL-safe slug from human-readable text.\n * @param value Source text used to build the slug.\n * @returns A normalized, lowercase slug identifier.\n */",
    "signature": "export const slugify = (value: string): string =>",
    "filePath": "src/lib/plugin-internals/helpers.ts",
    "line": 11,
    "displayPath": "src/lib/plugin-internals/helpers.ts:11",
    "params": [
      {
        "name": "param",
        "value": "value Source text used to build the slug."
      }
    ],
    "returns": "A normalized, lowercase slug identifier.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/lib/plugin-internals/helpers.ts:26",
    "slug": "jsdoc-line-cleaner-26",
    "group": "Parser Helpers",
    "title": "JSDoc Line Cleaner",
    "summary": "Removes leading JSDoc formatting tokens from a single comment line.",
    "description": "Removes leading JSDoc formatting tokens from a single comment line.",
    "jsdocRaw": "/**\n * @auto-doc\n * @title JSDoc Line Cleaner\n * @group Parser Helpers\n * Removes leading JSDoc formatting tokens from a single comment line.\n * @param line Raw line captured from a JSDoc comment block.\n * @returns A cleaned line ready for parsing.\n */",
    "signature": "export const cleanJSDocLine = (line: string): string => line.replace(/^\\s*\\* ?/, '').trimEnd();",
    "filePath": "src/lib/plugin-internals/helpers.ts",
    "line": 26,
    "displayPath": "src/lib/plugin-internals/helpers.ts:26",
    "params": [
      {
        "name": "param",
        "value": "line Raw line captured from a JSDoc comment block."
      }
    ],
    "returns": "A cleaned line ready for parsing.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/lib/plugin-internals/helpers.ts:36",
    "slug": "entry-identifier-builder-36",
    "group": "Parser Helpers",
    "title": "Entry Identifier Builder",
    "summary": "Generates a deterministic identifier from relative file path and line number.",
    "description": "Generates a deterministic identifier from relative file path and line number.",
    "jsdocRaw": "/**\n * @auto-doc\n * @title Entry Identifier Builder\n * @group Parser Helpers\n * Generates a deterministic identifier from relative file path and line number.\n * @param filePath Workspace-relative path for the source file.\n * @param line 1-based source line where the JSDoc block starts.\n * @returns A stable entry id in `path:line` format.\n */",
    "signature": "export const createId = (filePath: string, line: number): string => `${filePath}:${line}`;",
    "filePath": "src/lib/plugin-internals/helpers.ts",
    "line": 36,
    "displayPath": "src/lib/plugin-internals/helpers.ts:36",
    "params": [
      {
        "name": "param",
        "value": "filePath Workspace-relative path for the source file."
      },
      {
        "name": "param",
        "value": "line 1-based source line where the JSDoc block starts."
      }
    ],
    "returns": "A stable entry id in `path:line` format.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/lib/plugin-internals/helpers.ts:47",
    "slug": "signature-title-inference-47",
    "group": "Parser Helpers",
    "title": "Signature Title Inference",
    "summary": "Infers an entry title from the signature line when no explicit override is provided.",
    "description": "Infers an entry title from the signature line when no explicit override is provided.",
    "jsdocRaw": "/**\n * @auto-doc\n * @title Signature Title Inference\n * @group Parser Helpers\n * Infers an entry title from the signature line when no explicit override is provided.\n * @param signature First non-empty line after a matched JSDoc block.\n * @param fallback Fallback name used when no symbol can be inferred.\n * @returns The inferred symbol name or the fallback value.\n */",
    "signature": "export const inferTitleFromSignature = (signature: string, fallback: string): string => {",
    "filePath": "src/lib/plugin-internals/helpers.ts",
    "line": 47,
    "displayPath": "src/lib/plugin-internals/helpers.ts:47",
    "params": [
      {
        "name": "param",
        "value": "signature First non-empty line after a matched JSDoc block."
      },
      {
        "name": "param",
        "value": "fallback Fallback name used when no symbol can be inferred."
      }
    ],
    "returns": "The inferred symbol name or the fallback value.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/lib/plugin-internals/helpers.ts:67",
    "slug": "signature-locator-67",
    "group": "Parser Helpers",
    "title": "Signature Locator",
    "summary": "Finds the next likely declaration/signature line after a matched JSDoc block.",
    "description": "Finds the next likely declaration/signature line after a matched JSDoc block.",
    "jsdocRaw": "/**\n * @auto-doc\n * @title Signature Locator\n * @group Parser Helpers\n * Finds the next likely declaration/signature line after a matched JSDoc block.\n * @param fileContent Full file content containing the matched block.\n * @param blockEnd End index of the matched JSDoc block.\n * @returns The first non-empty, non-comment line after the block.\n */",
    "signature": "export const signatureAfterBlock = (fileContent: string, blockEnd: number): string => {",
    "filePath": "src/lib/plugin-internals/helpers.ts",
    "line": 67,
    "displayPath": "src/lib/plugin-internals/helpers.ts:67",
    "params": [
      {
        "name": "param",
        "value": "fileContent Full file content containing the matched block."
      },
      {
        "name": "param",
        "value": "blockEnd End index of the matched JSDoc block."
      }
    ],
    "returns": "The first non-empty, non-comment line after the block.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/lib/plugin-internals/output.ts:12",
    "slug": "generated-module-emitter-12",
    "group": "Output",
    "title": "Generated Module Emitter",
    "summary": "Produces the generated TypeScript module consumed by docs routes.",
    "description": "Produces the generated TypeScript module consumed by docs routes.",
    "jsdocRaw": "/**\n * @auto-doc\n * @title Generated Module Emitter\n * @group Output\n * Produces the generated TypeScript module consumed by docs routes.\n * @param docs Parsed docs entries to serialize.\n * @returns TypeScript source code for `src/routes/docs/generated.ts`.\n */",
    "signature": "export const createGeneratedModule = (",
    "filePath": "src/lib/plugin-internals/output.ts",
    "line": 12,
    "displayPath": "src/lib/plugin-internals/output.ts:12",
    "params": [
      {
        "name": "param",
        "value": "docs Parsed docs entries to serialize."
      }
    ],
    "returns": "TypeScript source code for `src/routes/docs/generated.ts`.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/lib/plugin-internals/output.ts:48",
    "slug": "docs-settings-module-emitter-48",
    "group": "Output",
    "title": "Docs Settings Module Emitter",
    "summary": "Emits a tiny settings module used by docs routes to determine runtime visibility.",
    "description": "Emits a tiny settings module used by docs routes to determine runtime visibility.",
    "jsdocRaw": "/**\n * @auto-doc\n * @title Docs Settings Module Emitter\n * @group Output\n * Emits a tiny settings module used by docs routes to determine runtime visibility.\n * @param enabled Whether docs routes should be visible in the current build mode.\n * @returns TypeScript source for `src/routes/docs/settings.ts`.\n */",
    "signature": "export const createDocsSettingsModule = (enabled: boolean): string => {",
    "filePath": "src/lib/plugin-internals/output.ts",
    "line": 48,
    "displayPath": "src/lib/plugin-internals/output.ts:48",
    "params": [
      {
        "name": "param",
        "value": "enabled Whether docs routes should be visible in the current build mode."
      }
    ],
    "returns": "TypeScript source for `src/routes/docs/settings.ts`.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/lib/plugin-internals/output.ts:60",
    "slug": "docs-layout-load-emitter-60",
    "group": "Output",
    "title": "Docs Layout Load Emitter",
    "summary": "Produces generated load logic for `/docs/+layout.ts`.",
    "description": "Produces generated load logic for `/docs/+layout.ts`.",
    "jsdocRaw": "/**\n * @auto-doc\n * @title Docs Layout Load Emitter\n * @group Output\n * Produces generated load logic for `/docs/+layout.ts`.\n * @returns TypeScript source for shared docs layout data and visibility guard.\n */",
    "signature": "export const createDocsLayoutTsModule = (): string => {",
    "filePath": "src/lib/plugin-internals/output.ts",
    "line": 60,
    "displayPath": "src/lib/plugin-internals/output.ts:60",
    "params": [],
    "returns": "TypeScript source for shared docs layout data and visibility guard.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/lib/plugin-internals/output.ts:102",
    "slug": "docs-layout-scaffold-emitter-102",
    "group": "Output",
    "title": "Docs Layout Scaffold Emitter",
    "summary": "Produces the generated `/docs/+layout.svelte` scaffold consumed by projects using the plugin.",
    "description": "Produces the generated `/docs/+layout.svelte` scaffold consumed by projects using the plugin.",
    "jsdocRaw": "/**\n * @auto-doc\n * @title Docs Layout Scaffold Emitter\n * @group Output\n * Produces the generated `/docs/+layout.svelte` scaffold consumed by projects using the plugin.\n * @param docsTitle Sidebar heading shown above docs navigation.\n * @returns Svelte source for docs navigation layout with fuzzy search support.\n */",
    "signature": "export const createDocsLayoutSvelteModule = (",
    "filePath": "src/lib/plugin-internals/output.ts",
    "line": 102,
    "displayPath": "src/lib/plugin-internals/output.ts:102",
    "params": [
      {
        "name": "param",
        "value": "docsTitle Sidebar heading shown above docs navigation."
      }
    ],
    "returns": "Svelte source for docs navigation layout with fuzzy search support.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/lib/plugin-internals/output.ts:364",
    "slug": "docs-index-load-emitter-364",
    "group": "Output",
    "title": "Docs Index Load Emitter",
    "summary": "Produces generated load logic for `/docs/+page.ts`.",
    "description": "Produces generated load logic for `/docs/+page.ts`.",
    "jsdocRaw": "/**\n * @auto-doc\n * @title Docs Index Load Emitter\n * @group Output\n * Produces generated load logic for `/docs/+page.ts`.\n * @returns TypeScript source that provides sorted docs list and generation timestamp.\n */",
    "signature": "export const createDocsIndexPageTsModule = (): string => {",
    "filePath": "src/lib/plugin-internals/output.ts",
    "line": 364,
    "displayPath": "src/lib/plugin-internals/output.ts:364",
    "params": [],
    "returns": "TypeScript source that provides sorted docs list and generation timestamp.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/lib/plugin-internals/output.ts:390",
    "slug": "docs-index-page-emitter-390",
    "group": "Output",
    "title": "Docs Index Page Emitter",
    "summary": "Produces generated UI source for `/docs/+page.svelte`.",
    "description": "Produces generated UI source for `/docs/+page.svelte`.",
    "jsdocRaw": "/**\n * @auto-doc\n * @title Docs Index Page Emitter\n * @group Output\n * Produces generated UI source for `/docs/+page.svelte`.\n * @returns Svelte source for docs overview grouped listing.\n */",
    "signature": "export const createDocsIndexPageSvelteModule = (indexOptions: JsAutoDocsIndexOptions = {}): string => {",
    "filePath": "src/lib/plugin-internals/output.ts",
    "line": 390,
    "displayPath": "src/lib/plugin-internals/output.ts:390",
    "params": [],
    "returns": "Svelte source for docs overview grouped listing.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/lib/plugin-internals/output.ts:554",
    "slug": "group-detail-load-emitter-554",
    "group": "Output",
    "title": "Group Detail Load Emitter",
    "summary": "Produces generated load logic for `/docs/groups/[group]/+page.ts`.",
    "description": "Produces generated load logic for `/docs/groups/[group]/+page.ts`.",
    "jsdocRaw": "/**\n * @auto-doc\n * @title Group Detail Load Emitter\n * @group Output\n * Produces generated load logic for `/docs/groups/[group]/+page.ts`.\n * @returns TypeScript source for docs group landing page data.\n */",
    "signature": "export const createDocsGroupPageTsModule = (): string => {",
    "filePath": "src/lib/plugin-internals/output.ts",
    "line": 554,
    "displayPath": "src/lib/plugin-internals/output.ts:554",
    "params": [],
    "returns": "TypeScript source for docs group landing page data.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/lib/plugin-internals/output.ts:631",
    "slug": "group-detail-page-emitter-631",
    "group": "Output",
    "title": "Group Detail Page Emitter",
    "summary": "Produces generated UI source for `/docs/groups/[group]/+page.svelte`.",
    "description": "Produces generated UI source for `/docs/groups/[group]/+page.svelte`.",
    "jsdocRaw": "/**\n * @auto-doc\n * @title Group Detail Page Emitter\n * @group Output\n * Produces generated UI source for `/docs/groups/[group]/+page.svelte`.\n * @returns Svelte source for a docs group landing page.\n */",
    "signature": "export const createDocsGroupPageSvelteModule = (): string => {",
    "filePath": "src/lib/plugin-internals/output.ts",
    "line": 631,
    "displayPath": "src/lib/plugin-internals/output.ts:631",
    "params": [],
    "returns": "Svelte source for a docs group landing page.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/lib/plugin-internals/output.ts:713",
    "slug": "docs-detail-load-emitter-713",
    "group": "Output",
    "title": "Docs Detail Load Emitter",
    "summary": "Produces generated load logic for `/docs/[slug]/+page.ts` including author matching.",
    "description": "Produces generated load logic for `/docs/[slug]/+page.ts` including author matching.",
    "jsdocRaw": "/**\n * @auto-doc\n * @title Docs Detail Load Emitter\n * @group Output\n * Produces generated load logic for `/docs/[slug]/+page.ts` including author matching.\n * @returns TypeScript source for slug detail loader.\n */",
    "signature": "export const createDocsSlugPageTsModule = (): string => {",
    "filePath": "src/lib/plugin-internals/output.ts",
    "line": 713,
    "displayPath": "src/lib/plugin-internals/output.ts:713",
    "params": [],
    "returns": "TypeScript source for slug detail loader.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/lib/plugin-internals/output.ts:768",
    "slug": "docs-detail-page-emitter-768",
    "group": "Output",
    "title": "Docs Detail Page Emitter",
    "summary": "Produces generated UI source for `/docs/[slug]/+page.svelte`.",
    "description": "Produces generated UI source for `/docs/[slug]/+page.svelte`.",
    "jsdocRaw": "/**\n * @auto-doc\n * @title Docs Detail Page Emitter\n * @group Output\n * Produces generated UI source for `/docs/[slug]/+page.svelte`.\n * @returns Svelte source for docs detail with author card and contrast-safe light mode.\n */",
    "signature": "export const createDocsSlugPageSvelteModule = (collapseJson = false): string => {",
    "filePath": "src/lib/plugin-internals/output.ts",
    "line": 768,
    "displayPath": "src/lib/plugin-internals/output.ts:768",
    "params": [],
    "returns": "Svelte source for docs detail with author card and contrast-safe light mode.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/lib/plugin-internals/output.ts:1292",
    "slug": "version-detail-load-emitter-1292",
    "group": "Output",
    "title": "Version Detail Load Emitter",
    "summary": "Produces generated load logic for `/docs/[slug]/versions/[version]/+page.ts`.",
    "description": "Produces generated load logic for `/docs/[slug]/versions/[version]/+page.ts`.",
    "jsdocRaw": "/**\n * @auto-doc\n * @title Version Detail Load Emitter\n * @group Output\n * Produces generated load logic for `/docs/[slug]/versions/[version]/+page.ts`.\n * @returns TypeScript source for selected version diff data.\n */",
    "signature": "export const createDocsVersionPageTsModule = (): string => {",
    "filePath": "src/lib/plugin-internals/output.ts",
    "line": 1292,
    "displayPath": "src/lib/plugin-internals/output.ts:1292",
    "params": [],
    "returns": "TypeScript source for selected version diff data.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/lib/plugin-internals/output.ts:1386",
    "slug": "version-detail-page-emitter-1386",
    "group": "Output",
    "title": "Version Detail Page Emitter",
    "summary": "Produces generated UI source for `/docs/[slug]/versions/[version]/+page.svelte`.",
    "description": "Produces generated UI source for `/docs/[slug]/versions/[version]/+page.svelte`.",
    "jsdocRaw": "/**\n * @auto-doc\n * @title Version Detail Page Emitter\n * @group Output\n * Produces generated UI source for `/docs/[slug]/versions/[version]/+page.svelte`.\n * @returns Svelte source for a \"what changed\" version details page.\n */",
    "signature": "export const createDocsVersionPageSvelteModule = (): string => {",
    "filePath": "src/lib/plugin-internals/output.ts",
    "line": 1386,
    "displayPath": "src/lib/plugin-internals/output.ts:1386",
    "params": [],
    "returns": "Svelte source for a \"what changed\" version details page.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/lib/plugin-internals/output.ts:1462",
    "slug": "author-profile-load-emitter-1462",
    "group": "Output",
    "title": "Author Profile Load Emitter",
    "summary": "Produces generated load logic for `/docs/authors/[authorKey]/+page.ts`.",
    "description": "Produces generated load logic for `/docs/authors/[authorKey]/+page.ts`.",
    "jsdocRaw": "/**\n * @auto-doc\n * @title Author Profile Load Emitter\n * @group Output\n * Produces generated load logic for `/docs/authors/[authorKey]/+page.ts`.\n * @returns TypeScript source for author profile data loading.\n */",
    "signature": "export const createDocsAuthorPageTsModule = (): string => {",
    "filePath": "src/lib/plugin-internals/output.ts",
    "line": 1462,
    "displayPath": "src/lib/plugin-internals/output.ts:1462",
    "params": [],
    "returns": "TypeScript source for author profile data loading.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/lib/plugin-internals/output.ts:1495",
    "slug": "author-profile-page-emitter-1495",
    "group": "Output",
    "title": "Author Profile Page Emitter",
    "summary": "Produces generated UI source for `/docs/authors/[authorKey]/+page.svelte`.",
    "description": "Produces generated UI source for `/docs/authors/[authorKey]/+page.svelte`.",
    "jsdocRaw": "/**\n * @auto-doc\n * @title Author Profile Page Emitter\n * @group Output\n * Produces generated UI source for `/docs/authors/[authorKey]/+page.svelte`.\n * @returns Svelte source for author profile page with conditional contact sections.\n */",
    "signature": "export const createDocsAuthorPageSvelteModule = (): string => {",
    "filePath": "src/lib/plugin-internals/output.ts",
    "line": 1495,
    "displayPath": "src/lib/plugin-internals/output.ts:1495",
    "params": [],
    "returns": "Svelte source for author profile page with conditional contact sections.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/lib/plugin-internals/parser.ts:7",
    "slug": "auto-doc-block-parser-7",
    "group": "Parser Core",
    "title": "Auto-Doc Block Parser",
    "summary": "Parses a JSDoc block into a structured docs entry when it starts with `@auto-doc`.",
    "description": "Parses a JSDoc block into a structured docs entry when it starts with `@auto-doc`.\nSupports tags for `@param`, `@returns`, `@response`, `@example`, `@group`, `@title`, and `@description`.",
    "jsdocRaw": "/**\n * @auto-doc\n * @title Auto-Doc Block Parser\n * @group Parser Core\n * Parses a JSDoc block into a structured docs entry when it starts with `@auto-doc`.\n * Supports tags for `@param`, `@returns`, `@response`, `@example`, `@group`, `@title`, and `@description`.\n * @param block Raw content captured inside a matched JSDoc block.\n * @param fileContent Full source file text.\n * @param blockStart Start index of the matched block.\n * @param blockEnd End index of the matched block.\n * @param filePath Workspace-relative source file path.\n * @returns A parsed docs entry or null if the block is not eligible.\n */",
    "signature": "export const parseBlock = (",
    "filePath": "src/lib/plugin-internals/parser.ts",
    "line": 7,
    "displayPath": "src/lib/plugin-internals/parser.ts:7",
    "params": [
      {
        "name": "param",
        "value": "block Raw content captured inside a matched JSDoc block."
      },
      {
        "name": "param",
        "value": "fileContent Full source file text."
      },
      {
        "name": "param",
        "value": "blockStart Start index of the matched block."
      },
      {
        "name": "param",
        "value": "blockEnd End index of the matched block."
      },
      {
        "name": "param",
        "value": "filePath Workspace-relative source file path."
      }
    ],
    "returns": "A parsed docs entry or null if the block is not eligible.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/lib/plugin-internals/parser.ts:156",
    "slug": "file-docs-extractor-156",
    "group": "Parser Core",
    "title": "File Docs Extractor",
    "summary": "Extracts all eligible auto-doc blocks from a source file.",
    "description": "Extracts all eligible auto-doc blocks from a source file.",
    "jsdocRaw": "/**\n * @auto-doc\n * @title File Docs Extractor\n * @group Parser Core\n * Extracts all eligible auto-doc blocks from a source file.\n * @param absolutePath Absolute file path being parsed.\n * @param root Workspace root used to produce relative paths in output.\n * @returns Parsed docs entries found in the file.\n */",
    "signature": "export const parseFileDocs = async (absolutePath: string, root: string): Promise<AutoDocEntry[]> => {",
    "filePath": "src/lib/plugin-internals/parser.ts",
    "line": 156,
    "displayPath": "src/lib/plugin-internals/parser.ts:156",
    "params": [
      {
        "name": "param",
        "value": "absolutePath Absolute file path being parsed."
      },
      {
        "name": "param",
        "value": "root Workspace root used to produce relative paths in output."
      }
    ],
    "returns": "Parsed docs entries found in the file.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/lib/plugin-internals/runtime.ts:45",
    "slug": "jsautodocs-plugin-factory-45",
    "group": "Plugin API",
    "title": "jsAutoDocs Plugin Factory",
    "summary": "Creates the Vite plugin that generates docs data from `@auto-doc` JSDoc blocks.",
    "description": "Creates the Vite plugin that generates docs data from `@auto-doc` JSDoc blocks.",
    "jsdocRaw": "/**\n * @auto-doc\n * @title jsAutoDocs Plugin Factory\n * @group Plugin API\n * Creates the Vite plugin that generates docs data from `@auto-doc` JSDoc blocks.\n * @param options Optional root, scan directory, output file, and extension settings.\n * @returns A Vite plugin instance that runs on build and dev server events.\n */",
    "signature": "export const jsAutoDocs = (options: JsAutoDocsOptions = {}): Plugin => {",
    "filePath": "src/lib/plugin-internals/runtime.ts",
    "line": 45,
    "displayPath": "src/lib/plugin-internals/runtime.ts:45",
    "params": [
      {
        "name": "param",
        "value": "options Optional root, scan directory, output file, and extension settings."
      }
    ],
    "returns": "A Vite plugin instance that runs on build and dev server events.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/lib/plugin-internals/runtime.ts:286",
    "slug": "docs-regeneration-routine-286",
    "group": "Plugin Runtime",
    "title": "Docs Regeneration Routine",
    "summary": "Regenerates docs output from the current source tree and writes the generated module.",
    "description": "Regenerates docs output from the current source tree and writes the generated module.",
    "jsdocRaw": "/**\n   * @auto-doc\n   * @title Docs Regeneration Routine\n   * @group Plugin Runtime\n   * Regenerates docs output from the current source tree and writes the generated module.\n   * @returns A promise that resolves when generation completes.\n   */",
    "signature": "const generateDocs = async (isProductionBuild: boolean): Promise<void> => {",
    "filePath": "src/lib/plugin-internals/runtime.ts",
    "line": 286,
    "displayPath": "src/lib/plugin-internals/runtime.ts:286",
    "params": [],
    "returns": "A promise that resolves when generation completes.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/lib/plugin-internals/runtime.ts:394",
    "slug": "watcher-change-handler-394",
    "group": "Plugin Runtime",
    "title": "Watcher Change Handler",
    "summary": "Handles file-system watcher changes and triggers docs regeneration when relevant.",
    "description": "Handles file-system watcher changes and triggers docs regeneration when relevant.",
    "jsdocRaw": "/**\n       * @auto-doc\n       * @title Watcher Change Handler\n       * @group Plugin Runtime\n       * Handles file-system watcher changes and triggers docs regeneration when relevant.\n       * @param changed File path emitted by the Vite watcher.\n       * @returns No value.\n       */",
    "signature": "const trigger = (changed: string): void => {",
    "filePath": "src/lib/plugin-internals/runtime.ts",
    "line": 394,
    "displayPath": "src/lib/plugin-internals/runtime.ts:394",
    "params": [
      {
        "name": "param",
        "value": "changed File path emitted by the Vite watcher."
      }
    ],
    "returns": "No value.",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  },
  {
    "id": "src/routes/+page.svelte:2",
    "slug": "example-page-2",
    "group": "Examples",
    "title": "Example Page",
    "summary": "No summary provided.",
    "description": "",
    "jsdocRaw": "/**\n\t * @auto-doc\n\t * @title Example Page\n\t * @description This is an example page demonstrating the usage of jsAutoDocs with SvelteKit\n\t * @group Examples\n\t */",
    "signature": "",
    "filePath": "src/routes/+page.svelte",
    "line": 2,
    "displayPath": "This is an example page demonstrating the usage of jsAutoDocs with SvelteKit",
    "params": [],
    "returns": "",
    "response": "",
    "examples": [],
    "tags": [],
    "lastModified": "2026-04-16T12:16:24.196Z",
    "versionHistory": [
      "26.04.16.1"
    ]
  }
];

export const authors: Record<string, GeneratedAuthorProfile> = {};

export const history: Record<string, GeneratedDocVersionRecord[]> = {
  "src/lib/plugin-internals/discovery.ts:5": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "File Discovery",
        "title": "Source File Walker",
        "summary": "Recursively walks the scan directory and collects source files matching configured extensions.",
        "description": "Recursively walks the scan directory and collects source files matching configured extensions.\nSkips ignored system/build directories and the generated output file itself.",
        "jsdocRaw": "/**\n * @auto-doc\n * @title Source File Walker\n * @group File Discovery\n * Recursively walks the scan directory and collects source files matching configured extensions.\n * Skips ignored system/build directories and the generated output file itself.\n * @param dir Current directory being traversed.\n * @param extensions Allowed file extensions.\n * @param outputFilePath Absolute path of the generated docs output file.\n * @returns A flat list of absolute source file paths.\n */",
        "signature": "export const walk = async (",
        "displayPath": "src/lib/plugin-internals/discovery.ts:5",
        "params": [
          {
            "name": "param",
            "value": "dir Current directory being traversed."
          },
          {
            "name": "param",
            "value": "extensions Allowed file extensions."
          },
          {
            "name": "param",
            "value": "outputFilePath Absolute path of the generated docs output file."
          }
        ],
        "returns": "A flat list of absolute source file paths.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/lib/plugin-internals/helpers.ts:1": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Plugin Internals",
        "title": "Path Normalizer",
        "summary": "Normalizes file separators for stable cross-platform path keys.",
        "description": "Normalizes file separators for stable cross-platform path keys.",
        "jsdocRaw": "/**\n * @auto-doc\n * @title Path Normalizer\n * @group Plugin Internals\n * Normalizes file separators for stable cross-platform path keys.\n * @param value Input path value that may include platform-specific separators.\n * @returns A slash-normalized path string.\n */",
        "signature": "export const normalize = (value: string): string => value.replaceAll('\\\\', '/');",
        "displayPath": "src/lib/plugin-internals/helpers.ts:1",
        "params": [
          {
            "name": "param",
            "value": "value Input path value that may include platform-specific separators."
          }
        ],
        "returns": "A slash-normalized path string.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/lib/plugin-internals/helpers.ts:11": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Plugin Internals",
        "title": "Slug Generator",
        "summary": "Creates a URL-safe slug from human-readable text.",
        "description": "Creates a URL-safe slug from human-readable text.",
        "jsdocRaw": "/**\n * @auto-doc\n * @title Slug Generator\n * @group Plugin Internals\n * Creates a URL-safe slug from human-readable text.\n * @param value Source text used to build the slug.\n * @returns A normalized, lowercase slug identifier.\n */",
        "signature": "export const slugify = (value: string): string =>",
        "displayPath": "src/lib/plugin-internals/helpers.ts:11",
        "params": [
          {
            "name": "param",
            "value": "value Source text used to build the slug."
          }
        ],
        "returns": "A normalized, lowercase slug identifier.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/lib/plugin-internals/helpers.ts:26": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Parser Helpers",
        "title": "JSDoc Line Cleaner",
        "summary": "Removes leading JSDoc formatting tokens from a single comment line.",
        "description": "Removes leading JSDoc formatting tokens from a single comment line.",
        "jsdocRaw": "/**\n * @auto-doc\n * @title JSDoc Line Cleaner\n * @group Parser Helpers\n * Removes leading JSDoc formatting tokens from a single comment line.\n * @param line Raw line captured from a JSDoc comment block.\n * @returns A cleaned line ready for parsing.\n */",
        "signature": "export const cleanJSDocLine = (line: string): string => line.replace(/^\\s*\\* ?/, '').trimEnd();",
        "displayPath": "src/lib/plugin-internals/helpers.ts:26",
        "params": [
          {
            "name": "param",
            "value": "line Raw line captured from a JSDoc comment block."
          }
        ],
        "returns": "A cleaned line ready for parsing.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/lib/plugin-internals/helpers.ts:36": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Parser Helpers",
        "title": "Entry Identifier Builder",
        "summary": "Generates a deterministic identifier from relative file path and line number.",
        "description": "Generates a deterministic identifier from relative file path and line number.",
        "jsdocRaw": "/**\n * @auto-doc\n * @title Entry Identifier Builder\n * @group Parser Helpers\n * Generates a deterministic identifier from relative file path and line number.\n * @param filePath Workspace-relative path for the source file.\n * @param line 1-based source line where the JSDoc block starts.\n * @returns A stable entry id in `path:line` format.\n */",
        "signature": "export const createId = (filePath: string, line: number): string => `${filePath}:${line}`;",
        "displayPath": "src/lib/plugin-internals/helpers.ts:36",
        "params": [
          {
            "name": "param",
            "value": "filePath Workspace-relative path for the source file."
          },
          {
            "name": "param",
            "value": "line 1-based source line where the JSDoc block starts."
          }
        ],
        "returns": "A stable entry id in `path:line` format.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/lib/plugin-internals/helpers.ts:47": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Parser Helpers",
        "title": "Signature Title Inference",
        "summary": "Infers an entry title from the signature line when no explicit override is provided.",
        "description": "Infers an entry title from the signature line when no explicit override is provided.",
        "jsdocRaw": "/**\n * @auto-doc\n * @title Signature Title Inference\n * @group Parser Helpers\n * Infers an entry title from the signature line when no explicit override is provided.\n * @param signature First non-empty line after a matched JSDoc block.\n * @param fallback Fallback name used when no symbol can be inferred.\n * @returns The inferred symbol name or the fallback value.\n */",
        "signature": "export const inferTitleFromSignature = (signature: string, fallback: string): string => {",
        "displayPath": "src/lib/plugin-internals/helpers.ts:47",
        "params": [
          {
            "name": "param",
            "value": "signature First non-empty line after a matched JSDoc block."
          },
          {
            "name": "param",
            "value": "fallback Fallback name used when no symbol can be inferred."
          }
        ],
        "returns": "The inferred symbol name or the fallback value.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/lib/plugin-internals/helpers.ts:67": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Parser Helpers",
        "title": "Signature Locator",
        "summary": "Finds the next likely declaration/signature line after a matched JSDoc block.",
        "description": "Finds the next likely declaration/signature line after a matched JSDoc block.",
        "jsdocRaw": "/**\n * @auto-doc\n * @title Signature Locator\n * @group Parser Helpers\n * Finds the next likely declaration/signature line after a matched JSDoc block.\n * @param fileContent Full file content containing the matched block.\n * @param blockEnd End index of the matched JSDoc block.\n * @returns The first non-empty, non-comment line after the block.\n */",
        "signature": "export const signatureAfterBlock = (fileContent: string, blockEnd: number): string => {",
        "displayPath": "src/lib/plugin-internals/helpers.ts:67",
        "params": [
          {
            "name": "param",
            "value": "fileContent Full file content containing the matched block."
          },
          {
            "name": "param",
            "value": "blockEnd End index of the matched JSDoc block."
          }
        ],
        "returns": "The first non-empty, non-comment line after the block.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/lib/plugin-internals/output.ts:12": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Output",
        "title": "Generated Module Emitter",
        "summary": "Produces the generated TypeScript module consumed by docs routes.",
        "description": "Produces the generated TypeScript module consumed by docs routes.",
        "jsdocRaw": "/**\n * @auto-doc\n * @title Generated Module Emitter\n * @group Output\n * Produces the generated TypeScript module consumed by docs routes.\n * @param docs Parsed docs entries to serialize.\n * @returns TypeScript source code for `src/routes/docs/generated.ts`.\n */",
        "signature": "export const createGeneratedModule = (",
        "displayPath": "src/lib/plugin-internals/output.ts:12",
        "params": [
          {
            "name": "param",
            "value": "docs Parsed docs entries to serialize."
          }
        ],
        "returns": "TypeScript source code for `src/routes/docs/generated.ts`.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/lib/plugin-internals/output.ts:48": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Output",
        "title": "Docs Settings Module Emitter",
        "summary": "Emits a tiny settings module used by docs routes to determine runtime visibility.",
        "description": "Emits a tiny settings module used by docs routes to determine runtime visibility.",
        "jsdocRaw": "/**\n * @auto-doc\n * @title Docs Settings Module Emitter\n * @group Output\n * Emits a tiny settings module used by docs routes to determine runtime visibility.\n * @param enabled Whether docs routes should be visible in the current build mode.\n * @returns TypeScript source for `src/routes/docs/settings.ts`.\n */",
        "signature": "export const createDocsSettingsModule = (enabled: boolean): string => {",
        "displayPath": "src/lib/plugin-internals/output.ts:48",
        "params": [
          {
            "name": "param",
            "value": "enabled Whether docs routes should be visible in the current build mode."
          }
        ],
        "returns": "TypeScript source for `src/routes/docs/settings.ts`.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/lib/plugin-internals/output.ts:60": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Output",
        "title": "Docs Layout Load Emitter",
        "summary": "Produces generated load logic for `/docs/+layout.ts`.",
        "description": "Produces generated load logic for `/docs/+layout.ts`.",
        "jsdocRaw": "/**\n * @auto-doc\n * @title Docs Layout Load Emitter\n * @group Output\n * Produces generated load logic for `/docs/+layout.ts`.\n * @returns TypeScript source for shared docs layout data and visibility guard.\n */",
        "signature": "export const createDocsLayoutTsModule = (): string => {",
        "displayPath": "src/lib/plugin-internals/output.ts:60",
        "params": [],
        "returns": "TypeScript source for shared docs layout data and visibility guard.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/lib/plugin-internals/output.ts:102": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Output",
        "title": "Docs Layout Scaffold Emitter",
        "summary": "Produces the generated `/docs/+layout.svelte` scaffold consumed by projects using the plugin.",
        "description": "Produces the generated `/docs/+layout.svelte` scaffold consumed by projects using the plugin.",
        "jsdocRaw": "/**\n * @auto-doc\n * @title Docs Layout Scaffold Emitter\n * @group Output\n * Produces the generated `/docs/+layout.svelte` scaffold consumed by projects using the plugin.\n * @param docsTitle Sidebar heading shown above docs navigation.\n * @returns Svelte source for docs navigation layout with fuzzy search support.\n */",
        "signature": "export const createDocsLayoutSvelteModule = (",
        "displayPath": "src/lib/plugin-internals/output.ts:102",
        "params": [
          {
            "name": "param",
            "value": "docsTitle Sidebar heading shown above docs navigation."
          }
        ],
        "returns": "Svelte source for docs navigation layout with fuzzy search support.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/lib/plugin-internals/output.ts:364": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Output",
        "title": "Docs Index Load Emitter",
        "summary": "Produces generated load logic for `/docs/+page.ts`.",
        "description": "Produces generated load logic for `/docs/+page.ts`.",
        "jsdocRaw": "/**\n * @auto-doc\n * @title Docs Index Load Emitter\n * @group Output\n * Produces generated load logic for `/docs/+page.ts`.\n * @returns TypeScript source that provides sorted docs list and generation timestamp.\n */",
        "signature": "export const createDocsIndexPageTsModule = (): string => {",
        "displayPath": "src/lib/plugin-internals/output.ts:364",
        "params": [],
        "returns": "TypeScript source that provides sorted docs list and generation timestamp.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/lib/plugin-internals/output.ts:390": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Output",
        "title": "Docs Index Page Emitter",
        "summary": "Produces generated UI source for `/docs/+page.svelte`.",
        "description": "Produces generated UI source for `/docs/+page.svelte`.",
        "jsdocRaw": "/**\n * @auto-doc\n * @title Docs Index Page Emitter\n * @group Output\n * Produces generated UI source for `/docs/+page.svelte`.\n * @returns Svelte source for docs overview grouped listing.\n */",
        "signature": "export const createDocsIndexPageSvelteModule = (indexOptions: JsAutoDocsIndexOptions = {}): string => {",
        "displayPath": "src/lib/plugin-internals/output.ts:390",
        "params": [],
        "returns": "Svelte source for docs overview grouped listing.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/lib/plugin-internals/output.ts:554": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Output",
        "title": "Group Detail Load Emitter",
        "summary": "Produces generated load logic for `/docs/groups/[group]/+page.ts`.",
        "description": "Produces generated load logic for `/docs/groups/[group]/+page.ts`.",
        "jsdocRaw": "/**\n * @auto-doc\n * @title Group Detail Load Emitter\n * @group Output\n * Produces generated load logic for `/docs/groups/[group]/+page.ts`.\n * @returns TypeScript source for docs group landing page data.\n */",
        "signature": "export const createDocsGroupPageTsModule = (): string => {",
        "displayPath": "src/lib/plugin-internals/output.ts:554",
        "params": [],
        "returns": "TypeScript source for docs group landing page data.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/lib/plugin-internals/output.ts:631": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Output",
        "title": "Group Detail Page Emitter",
        "summary": "Produces generated UI source for `/docs/groups/[group]/+page.svelte`.",
        "description": "Produces generated UI source for `/docs/groups/[group]/+page.svelte`.",
        "jsdocRaw": "/**\n * @auto-doc\n * @title Group Detail Page Emitter\n * @group Output\n * Produces generated UI source for `/docs/groups/[group]/+page.svelte`.\n * @returns Svelte source for a docs group landing page.\n */",
        "signature": "export const createDocsGroupPageSvelteModule = (): string => {",
        "displayPath": "src/lib/plugin-internals/output.ts:631",
        "params": [],
        "returns": "Svelte source for a docs group landing page.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/lib/plugin-internals/output.ts:713": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Output",
        "title": "Docs Detail Load Emitter",
        "summary": "Produces generated load logic for `/docs/[slug]/+page.ts` including author matching.",
        "description": "Produces generated load logic for `/docs/[slug]/+page.ts` including author matching.",
        "jsdocRaw": "/**\n * @auto-doc\n * @title Docs Detail Load Emitter\n * @group Output\n * Produces generated load logic for `/docs/[slug]/+page.ts` including author matching.\n * @returns TypeScript source for slug detail loader.\n */",
        "signature": "export const createDocsSlugPageTsModule = (): string => {",
        "displayPath": "src/lib/plugin-internals/output.ts:713",
        "params": [],
        "returns": "TypeScript source for slug detail loader.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/lib/plugin-internals/output.ts:768": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Output",
        "title": "Docs Detail Page Emitter",
        "summary": "Produces generated UI source for `/docs/[slug]/+page.svelte`.",
        "description": "Produces generated UI source for `/docs/[slug]/+page.svelte`.",
        "jsdocRaw": "/**\n * @auto-doc\n * @title Docs Detail Page Emitter\n * @group Output\n * Produces generated UI source for `/docs/[slug]/+page.svelte`.\n * @returns Svelte source for docs detail with author card and contrast-safe light mode.\n */",
        "signature": "export const createDocsSlugPageSvelteModule = (collapseJson = false): string => {",
        "displayPath": "src/lib/plugin-internals/output.ts:768",
        "params": [],
        "returns": "Svelte source for docs detail with author card and contrast-safe light mode.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/lib/plugin-internals/output.ts:1292": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Output",
        "title": "Version Detail Load Emitter",
        "summary": "Produces generated load logic for `/docs/[slug]/versions/[version]/+page.ts`.",
        "description": "Produces generated load logic for `/docs/[slug]/versions/[version]/+page.ts`.",
        "jsdocRaw": "/**\n * @auto-doc\n * @title Version Detail Load Emitter\n * @group Output\n * Produces generated load logic for `/docs/[slug]/versions/[version]/+page.ts`.\n * @returns TypeScript source for selected version diff data.\n */",
        "signature": "export const createDocsVersionPageTsModule = (): string => {",
        "displayPath": "src/lib/plugin-internals/output.ts:1292",
        "params": [],
        "returns": "TypeScript source for selected version diff data.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/lib/plugin-internals/output.ts:1386": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Output",
        "title": "Version Detail Page Emitter",
        "summary": "Produces generated UI source for `/docs/[slug]/versions/[version]/+page.svelte`.",
        "description": "Produces generated UI source for `/docs/[slug]/versions/[version]/+page.svelte`.",
        "jsdocRaw": "/**\n * @auto-doc\n * @title Version Detail Page Emitter\n * @group Output\n * Produces generated UI source for `/docs/[slug]/versions/[version]/+page.svelte`.\n * @returns Svelte source for a \"what changed\" version details page.\n */",
        "signature": "export const createDocsVersionPageSvelteModule = (): string => {",
        "displayPath": "src/lib/plugin-internals/output.ts:1386",
        "params": [],
        "returns": "Svelte source for a \"what changed\" version details page.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/lib/plugin-internals/output.ts:1462": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Output",
        "title": "Author Profile Load Emitter",
        "summary": "Produces generated load logic for `/docs/authors/[authorKey]/+page.ts`.",
        "description": "Produces generated load logic for `/docs/authors/[authorKey]/+page.ts`.",
        "jsdocRaw": "/**\n * @auto-doc\n * @title Author Profile Load Emitter\n * @group Output\n * Produces generated load logic for `/docs/authors/[authorKey]/+page.ts`.\n * @returns TypeScript source for author profile data loading.\n */",
        "signature": "export const createDocsAuthorPageTsModule = (): string => {",
        "displayPath": "src/lib/plugin-internals/output.ts:1462",
        "params": [],
        "returns": "TypeScript source for author profile data loading.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/lib/plugin-internals/output.ts:1495": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Output",
        "title": "Author Profile Page Emitter",
        "summary": "Produces generated UI source for `/docs/authors/[authorKey]/+page.svelte`.",
        "description": "Produces generated UI source for `/docs/authors/[authorKey]/+page.svelte`.",
        "jsdocRaw": "/**\n * @auto-doc\n * @title Author Profile Page Emitter\n * @group Output\n * Produces generated UI source for `/docs/authors/[authorKey]/+page.svelte`.\n * @returns Svelte source for author profile page with conditional contact sections.\n */",
        "signature": "export const createDocsAuthorPageSvelteModule = (): string => {",
        "displayPath": "src/lib/plugin-internals/output.ts:1495",
        "params": [],
        "returns": "Svelte source for author profile page with conditional contact sections.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/lib/plugin-internals/parser.ts:7": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Parser Core",
        "title": "Auto-Doc Block Parser",
        "summary": "Parses a JSDoc block into a structured docs entry when it starts with `@auto-doc`.",
        "description": "Parses a JSDoc block into a structured docs entry when it starts with `@auto-doc`.\nSupports tags for `@param`, `@returns`, `@response`, `@example`, `@group`, `@title`, and `@description`.",
        "jsdocRaw": "/**\n * @auto-doc\n * @title Auto-Doc Block Parser\n * @group Parser Core\n * Parses a JSDoc block into a structured docs entry when it starts with `@auto-doc`.\n * Supports tags for `@param`, `@returns`, `@response`, `@example`, `@group`, `@title`, and `@description`.\n * @param block Raw content captured inside a matched JSDoc block.\n * @param fileContent Full source file text.\n * @param blockStart Start index of the matched block.\n * @param blockEnd End index of the matched block.\n * @param filePath Workspace-relative source file path.\n * @returns A parsed docs entry or null if the block is not eligible.\n */",
        "signature": "export const parseBlock = (",
        "displayPath": "src/lib/plugin-internals/parser.ts:7",
        "params": [
          {
            "name": "param",
            "value": "block Raw content captured inside a matched JSDoc block."
          },
          {
            "name": "param",
            "value": "fileContent Full source file text."
          },
          {
            "name": "param",
            "value": "blockStart Start index of the matched block."
          },
          {
            "name": "param",
            "value": "blockEnd End index of the matched block."
          },
          {
            "name": "param",
            "value": "filePath Workspace-relative source file path."
          }
        ],
        "returns": "A parsed docs entry or null if the block is not eligible.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/lib/plugin-internals/parser.ts:156": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Parser Core",
        "title": "File Docs Extractor",
        "summary": "Extracts all eligible auto-doc blocks from a source file.",
        "description": "Extracts all eligible auto-doc blocks from a source file.",
        "jsdocRaw": "/**\n * @auto-doc\n * @title File Docs Extractor\n * @group Parser Core\n * Extracts all eligible auto-doc blocks from a source file.\n * @param absolutePath Absolute file path being parsed.\n * @param root Workspace root used to produce relative paths in output.\n * @returns Parsed docs entries found in the file.\n */",
        "signature": "export const parseFileDocs = async (absolutePath: string, root: string): Promise<AutoDocEntry[]> => {",
        "displayPath": "src/lib/plugin-internals/parser.ts:156",
        "params": [
          {
            "name": "param",
            "value": "absolutePath Absolute file path being parsed."
          },
          {
            "name": "param",
            "value": "root Workspace root used to produce relative paths in output."
          }
        ],
        "returns": "Parsed docs entries found in the file.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/lib/plugin-internals/runtime.ts:45": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Plugin API",
        "title": "jsAutoDocs Plugin Factory",
        "summary": "Creates the Vite plugin that generates docs data from `@auto-doc` JSDoc blocks.",
        "description": "Creates the Vite plugin that generates docs data from `@auto-doc` JSDoc blocks.",
        "jsdocRaw": "/**\n * @auto-doc\n * @title jsAutoDocs Plugin Factory\n * @group Plugin API\n * Creates the Vite plugin that generates docs data from `@auto-doc` JSDoc blocks.\n * @param options Optional root, scan directory, output file, and extension settings.\n * @returns A Vite plugin instance that runs on build and dev server events.\n */",
        "signature": "export const jsAutoDocs = (options: JsAutoDocsOptions = {}): Plugin => {",
        "displayPath": "src/lib/plugin-internals/runtime.ts:45",
        "params": [
          {
            "name": "param",
            "value": "options Optional root, scan directory, output file, and extension settings."
          }
        ],
        "returns": "A Vite plugin instance that runs on build and dev server events.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/lib/plugin-internals/runtime.ts:286": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Plugin Runtime",
        "title": "Docs Regeneration Routine",
        "summary": "Regenerates docs output from the current source tree and writes the generated module.",
        "description": "Regenerates docs output from the current source tree and writes the generated module.",
        "jsdocRaw": "/**\n   * @auto-doc\n   * @title Docs Regeneration Routine\n   * @group Plugin Runtime\n   * Regenerates docs output from the current source tree and writes the generated module.\n   * @returns A promise that resolves when generation completes.\n   */",
        "signature": "const generateDocs = async (isProductionBuild: boolean): Promise<void> => {",
        "displayPath": "src/lib/plugin-internals/runtime.ts:286",
        "params": [],
        "returns": "A promise that resolves when generation completes.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/lib/plugin-internals/runtime.ts:394": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Plugin Runtime",
        "title": "Watcher Change Handler",
        "summary": "Handles file-system watcher changes and triggers docs regeneration when relevant.",
        "description": "Handles file-system watcher changes and triggers docs regeneration when relevant.",
        "jsdocRaw": "/**\n       * @auto-doc\n       * @title Watcher Change Handler\n       * @group Plugin Runtime\n       * Handles file-system watcher changes and triggers docs regeneration when relevant.\n       * @param changed File path emitted by the Vite watcher.\n       * @returns No value.\n       */",
        "signature": "const trigger = (changed: string): void => {",
        "displayPath": "src/lib/plugin-internals/runtime.ts:394",
        "params": [
          {
            "name": "param",
            "value": "changed File path emitted by the Vite watcher."
          }
        ],
        "returns": "No value.",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ],
  "src/routes/+page.svelte:2": [
    {
      "version": "26.04.16.1",
      "changedAt": "2026-04-16T12:16:24.196Z",
      "snapshot": {
        "group": "Examples",
        "title": "Example Page",
        "summary": "No summary provided.",
        "description": "",
        "jsdocRaw": "/**\n\t * @auto-doc\n\t * @title Example Page\n\t * @description This is an example page demonstrating the usage of jsAutoDocs with SvelteKit\n\t * @group Examples\n\t */",
        "signature": "",
        "displayPath": "This is an example page demonstrating the usage of jsAutoDocs with SvelteKit",
        "params": [],
        "returns": "",
        "response": "",
        "examples": [],
        "tags": []
      }
    }
  ]
};
